//! GENERATED — do not edit; run `just codegen-vc`.
//!
//! Source: `dist/credentials.compact` in
//! `@midnight-ntwrk/credential-compact@0.2.0` (npm).
// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit by hand.

#![allow(
    clippy::all,
    dead_code,
    unused_imports,
    unused_variables,
    unused_parens,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals
)]

use std::marker::PhantomData;

use midnight_compact_runtime::*;

midnight_compact_runtime::check_runtime_version!("0.16.102");

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct SchemaRef {
    pub packageId: [u8; 32],
    pub schemaId: [u8; 32],
    pub majorVersion: u16,
    pub minorVersion: u16,
}
impl Aligned for SchemaRef {
    fn alignment() -> Alignment {
        Alignment::concat([
            &<[u8; 32] as Aligned>::alignment(),
            &<[u8; 32] as Aligned>::alignment(),
            &<u16 as Aligned>::alignment(),
            &<u16 as Aligned>::alignment(),
        ])
    }
}
impl FieldRepr for SchemaRef {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.packageId.field_repr(writer);
        self.schemaId.field_repr(writer);
        self.majorVersion.field_repr(writer);
        self.minorVersion.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.packageId.field_size()
            + self.schemaId.field_size()
            + self.majorVersion.field_size()
            + self.minorVersion.field_size()
    }
}
impl FromFieldRepr for SchemaRef {
    const FIELD_SIZE: usize = <[u8; 32] as FromFieldRepr>::FIELD_SIZE
        + <[u8; 32] as FromFieldRepr>::FIELD_SIZE
        + <u16 as FromFieldRepr>::FIELD_SIZE
        + <u16 as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let packageId = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let schemaId = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let majorVersion =
            <u16 as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <u16 as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <u16 as FromFieldRepr>::FIELD_SIZE;
        let minorVersion =
            <u16 as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <u16 as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <u16 as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(SchemaRef {
            packageId,
            schemaId,
            majorVersion,
            minorVersion,
        })
    }
}
impl From<SchemaRef> for midnight_compact_runtime::Value {
    fn from(s: SchemaRef) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.packageId));
        _v.push(midnight_compact_runtime::Value::from(s.schemaId));
        _v.push(midnight_compact_runtime::Value::from(s.majorVersion));
        _v.push(midnight_compact_runtime::Value::from(s.minorVersion));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for SchemaRef {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.packageId.binary_repr(writer);
        self.schemaId.binary_repr(writer);
        self.majorVersion.binary_repr(writer);
        self.minorVersion.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.packageId.binary_len()
            + self.schemaId.binary_len()
            + self.majorVersion.binary_len()
            + self.minorVersion.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct VerificationMethodRef {
    pub controllerAddress: ContractAddress,
    pub methodId: [u8; 32],
}
impl Aligned for VerificationMethodRef {
    fn alignment() -> Alignment {
        Alignment::concat([
            &<ContractAddress as Aligned>::alignment(),
            &<[u8; 32] as Aligned>::alignment(),
        ])
    }
}
impl FieldRepr for VerificationMethodRef {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.controllerAddress.field_repr(writer);
        self.methodId.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.controllerAddress.field_size() + self.methodId.field_size()
    }
}
impl FromFieldRepr for VerificationMethodRef {
    const FIELD_SIZE: usize = <ContractAddress as FromFieldRepr>::FIELD_SIZE + <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let controllerAddress = <ContractAddress as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <ContractAddress as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <ContractAddress as FromFieldRepr>::FIELD_SIZE;
        let methodId = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(VerificationMethodRef {
            controllerAddress,
            methodId,
        })
    }
}
impl From<VerificationMethodRef> for midnight_compact_runtime::Value {
    fn from(s: VerificationMethodRef) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.controllerAddress));
        _v.push(midnight_compact_runtime::Value::from(s.methodId));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for VerificationMethodRef {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.controllerAddress.binary_repr(writer);
        self.methodId.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.controllerAddress.binary_len() + self.methodId.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct NoPublicClaims {}
impl Aligned for NoPublicClaims {
    fn alignment() -> Alignment {
        Alignment::concat([])
    }
}
impl FieldRepr for NoPublicClaims {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {}
    fn field_size(&self) -> usize {
        0
    }
}
impl FromFieldRepr for NoPublicClaims {
    const FIELD_SIZE: usize = 0;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        let mut _offset = 0usize;
        let _ = _offset;
        Some(NoPublicClaims {})
    }
}
impl From<NoPublicClaims> for midnight_compact_runtime::Value {
    fn from(s: NoPublicClaims) -> midnight_compact_runtime::Value {
        midnight_compact_runtime::Value::concat(core::iter::empty::<&midnight_compact_runtime::Value>())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for NoPublicClaims {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        let _ = writer;
    }
    fn binary_len(&self) -> usize {
        0
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct NoClaimCommitments {}
impl Aligned for NoClaimCommitments {
    fn alignment() -> Alignment {
        Alignment::concat([])
    }
}
impl FieldRepr for NoClaimCommitments {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {}
    fn field_size(&self) -> usize {
        0
    }
}
impl FromFieldRepr for NoClaimCommitments {
    const FIELD_SIZE: usize = 0;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        let mut _offset = 0usize;
        let _ = _offset;
        Some(NoClaimCommitments {})
    }
}
impl From<NoClaimCommitments> for midnight_compact_runtime::Value {
    fn from(s: NoClaimCommitments) -> midnight_compact_runtime::Value {
        midnight_compact_runtime::Value::concat(core::iter::empty::<&midnight_compact_runtime::Value>())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for NoClaimCommitments {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        let _ = writer;
    }
    fn binary_len(&self) -> usize {
        0
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct Signature {
    pub r: JubjubPoint,
    pub s: Fr,
}
impl Aligned for Signature {
    fn alignment() -> Alignment {
        Alignment::concat([&<JubjubPoint as Aligned>::alignment(), &<Fr as Aligned>::alignment()])
    }
}
impl FieldRepr for Signature {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        midnight_compact_runtime::jubjub_point_field_repr(&self.r, writer);
        self.s.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        midnight_compact_runtime::jubjub_point_field_size(&self.r) + self.s.field_size()
    }
}
impl FromFieldRepr for Signature {
    const FIELD_SIZE: usize = midnight_compact_runtime::JUBJUB_POINT_FIELD_SIZE + <Fr as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let r = midnight_compact_runtime::jubjub_point_from_field_repr(
            &_repr[_offset.._offset + midnight_compact_runtime::JUBJUB_POINT_FIELD_SIZE],
        )?;
        _offset += midnight_compact_runtime::JUBJUB_POINT_FIELD_SIZE;
        let s = <Fr as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <Fr as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <Fr as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(Signature { r, s })
    }
}
impl From<Signature> for midnight_compact_runtime::Value {
    fn from(s: Signature) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.r));
        _v.push(midnight_compact_runtime::Value::from(s.s));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for Signature {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        midnight_compact_runtime::jubjub_point_binary_repr(&self.r, writer);
        self.s.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        midnight_compact_runtime::jubjub_point_binary_len(&self.r) + self.s.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct ExplicitHolderBinding {
    pub holderVerificationMethodRef: VerificationMethodRef,
}
impl Aligned for ExplicitHolderBinding {
    fn alignment() -> Alignment {
        Alignment::concat([&<VerificationMethodRef as Aligned>::alignment()])
    }
}
impl FieldRepr for ExplicitHolderBinding {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.holderVerificationMethodRef.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.holderVerificationMethodRef.field_size()
    }
}
impl FromFieldRepr for ExplicitHolderBinding {
    const FIELD_SIZE: usize = <VerificationMethodRef as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let holderVerificationMethodRef = <VerificationMethodRef as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <VerificationMethodRef as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <VerificationMethodRef as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(ExplicitHolderBinding {
            holderVerificationMethodRef,
        })
    }
}
impl From<ExplicitHolderBinding> for midnight_compact_runtime::Value {
    fn from(s: ExplicitHolderBinding) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.holderVerificationMethodRef));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for ExplicitHolderBinding {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.holderVerificationMethodRef.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.holderVerificationMethodRef.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct Proof {
    pub signerVerificationMethodRef: VerificationMethodRef,
    pub createdAt: u64,
    pub challengeHash: [u8; 32],
    pub publicKey: JubjubPoint,
    pub signature: Signature,
}
impl Aligned for Proof {
    fn alignment() -> Alignment {
        Alignment::concat([
            &<VerificationMethodRef as Aligned>::alignment(),
            &<u64 as Aligned>::alignment(),
            &<[u8; 32] as Aligned>::alignment(),
            &<JubjubPoint as Aligned>::alignment(),
            &<Signature as Aligned>::alignment(),
        ])
    }
}
impl FieldRepr for Proof {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.signerVerificationMethodRef.field_repr(writer);
        self.createdAt.field_repr(writer);
        self.challengeHash.field_repr(writer);
        midnight_compact_runtime::jubjub_point_field_repr(&self.publicKey, writer);
        self.signature.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.signerVerificationMethodRef.field_size()
            + self.createdAt.field_size()
            + self.challengeHash.field_size()
            + midnight_compact_runtime::jubjub_point_field_size(&self.publicKey)
            + self.signature.field_size()
    }
}
impl FromFieldRepr for Proof {
    const FIELD_SIZE: usize = <VerificationMethodRef as FromFieldRepr>::FIELD_SIZE
        + <u64 as FromFieldRepr>::FIELD_SIZE
        + <[u8; 32] as FromFieldRepr>::FIELD_SIZE
        + midnight_compact_runtime::JUBJUB_POINT_FIELD_SIZE
        + <Signature as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let signerVerificationMethodRef = <VerificationMethodRef as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <VerificationMethodRef as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <VerificationMethodRef as FromFieldRepr>::FIELD_SIZE;
        let createdAt =
            <u64 as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <u64 as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <u64 as FromFieldRepr>::FIELD_SIZE;
        let challengeHash = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let publicKey = midnight_compact_runtime::jubjub_point_from_field_repr(
            &_repr[_offset.._offset + midnight_compact_runtime::JUBJUB_POINT_FIELD_SIZE],
        )?;
        _offset += midnight_compact_runtime::JUBJUB_POINT_FIELD_SIZE;
        let signature = <Signature as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <Signature as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <Signature as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(Proof {
            signerVerificationMethodRef,
            createdAt,
            challengeHash,
            publicKey,
            signature,
        })
    }
}
impl From<Proof> for midnight_compact_runtime::Value {
    fn from(s: Proof) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.signerVerificationMethodRef));
        _v.push(midnight_compact_runtime::Value::from(s.createdAt));
        _v.push(midnight_compact_runtime::Value::from(s.challengeHash));
        _v.push(midnight_compact_runtime::Value::from(s.publicKey));
        _v.push(midnight_compact_runtime::Value::from(s.signature));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for Proof {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.signerVerificationMethodRef.binary_repr(writer);
        self.createdAt.binary_repr(writer);
        self.challengeHash.binary_repr(writer);
        midnight_compact_runtime::jubjub_point_binary_repr(&self.publicKey, writer);
        self.signature.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.signerVerificationMethodRef.binary_len()
            + self.createdAt.binary_len()
            + self.challengeHash.binary_len()
            + midnight_compact_runtime::jubjub_point_binary_len(&self.publicKey)
            + self.signature.binary_len()
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
#[repr(u8)]
pub enum SignerRole {
    #[default]
    issuer = 0,
    verifier = 1,
}
impl Aligned for SignerRole {
    fn alignment() -> Alignment {
        u8::alignment()
    }
}
impl FieldRepr for SignerRole {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        (*self as u8).field_repr(writer);
    }
    fn field_size(&self) -> usize {
        1
    }
}
impl FromFieldRepr for SignerRole {
    const FIELD_SIZE: usize = 1;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        let n = u8::from_field_repr(r)?;
        match n {
            0 => Some(Self::issuer),
            1 => Some(Self::verifier),
            _ => None,
        }
    }
}
impl From<SignerRole> for midnight_compact_runtime::Value {
    fn from(v: SignerRole) -> midnight_compact_runtime::Value {
        midnight_compact_runtime::Value::from(v as u8)
    }
}
impl midnight_compact_runtime::BinaryHashRepr for SignerRole {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        (*self as u8).binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        1
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
#[repr(u8)]
pub enum AuthorizationState {
    #[default]
    active = 0,
    suspended = 1,
    revoked = 2,
}
impl Aligned for AuthorizationState {
    fn alignment() -> Alignment {
        u8::alignment()
    }
}
impl FieldRepr for AuthorizationState {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        (*self as u8).field_repr(writer);
    }
    fn field_size(&self) -> usize {
        1
    }
}
impl FromFieldRepr for AuthorizationState {
    const FIELD_SIZE: usize = 1;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        let n = u8::from_field_repr(r)?;
        match n {
            0 => Some(Self::active),
            1 => Some(Self::suspended),
            2 => Some(Self::revoked),
            _ => None,
        }
    }
}
impl From<AuthorizationState> for midnight_compact_runtime::Value {
    fn from(v: AuthorizationState) -> midnight_compact_runtime::Value {
        midnight_compact_runtime::Value::from(v as u8)
    }
}
impl midnight_compact_runtime::BinaryHashRepr for AuthorizationState {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        (*self as u8).binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        1
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
#[repr(u8)]
pub enum VerificationRelationship {
    #[default]
    assertionMethod = 0,
    authentication = 1,
    capabilityInvocation = 2,
}
impl Aligned for VerificationRelationship {
    fn alignment() -> Alignment {
        u8::alignment()
    }
}
impl FieldRepr for VerificationRelationship {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        (*self as u8).field_repr(writer);
    }
    fn field_size(&self) -> usize {
        1
    }
}
impl FromFieldRepr for VerificationRelationship {
    const FIELD_SIZE: usize = 1;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        let n = u8::from_field_repr(r)?;
        match n {
            0 => Some(Self::assertionMethod),
            1 => Some(Self::authentication),
            2 => Some(Self::capabilityInvocation),
            _ => None,
        }
    }
}
impl From<VerificationRelationship> for midnight_compact_runtime::Value {
    fn from(v: VerificationRelationship) -> midnight_compact_runtime::Value {
        midnight_compact_runtime::Value::from(v as u8)
    }
}
impl midnight_compact_runtime::BinaryHashRepr for VerificationRelationship {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        (*self as u8).binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        1
    }
}
#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct AuthorizedSignerDescriptor {
    pub version: u16,
    pub authorizationId: [u8; 32],
    pub decisionSequence: u64,
    pub state: AuthorizationState,
    pub role: SignerRole,
    pub signerVerificationMethodRef: VerificationMethodRef,
    pub signerPublicKey: JubjubPoint,
    pub didStateVersion: u64,
    pub verificationRelationship: VerificationRelationship,
    pub scopeCommitment: [u8; 32],
    pub policyCommitment: [u8; 32],
}
impl Aligned for AuthorizedSignerDescriptor {
    fn alignment() -> Alignment {
        Alignment::concat([
            &<u16 as Aligned>::alignment(),
            &<[u8; 32] as Aligned>::alignment(),
            &<u64 as Aligned>::alignment(),
            &<AuthorizationState as Aligned>::alignment(),
            &<SignerRole as Aligned>::alignment(),
            &<VerificationMethodRef as Aligned>::alignment(),
            &<JubjubPoint as Aligned>::alignment(),
            &<u64 as Aligned>::alignment(),
            &<VerificationRelationship as Aligned>::alignment(),
            &<[u8; 32] as Aligned>::alignment(),
            &<[u8; 32] as Aligned>::alignment(),
        ])
    }
}
impl FieldRepr for AuthorizedSignerDescriptor {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.version.field_repr(writer);
        self.authorizationId.field_repr(writer);
        self.decisionSequence.field_repr(writer);
        self.state.field_repr(writer);
        self.role.field_repr(writer);
        self.signerVerificationMethodRef.field_repr(writer);
        midnight_compact_runtime::jubjub_point_field_repr(&self.signerPublicKey, writer);
        self.didStateVersion.field_repr(writer);
        self.verificationRelationship.field_repr(writer);
        self.scopeCommitment.field_repr(writer);
        self.policyCommitment.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.version.field_size()
            + self.authorizationId.field_size()
            + self.decisionSequence.field_size()
            + self.state.field_size()
            + self.role.field_size()
            + self.signerVerificationMethodRef.field_size()
            + midnight_compact_runtime::jubjub_point_field_size(&self.signerPublicKey)
            + self.didStateVersion.field_size()
            + self.verificationRelationship.field_size()
            + self.scopeCommitment.field_size()
            + self.policyCommitment.field_size()
    }
}
impl FromFieldRepr for AuthorizedSignerDescriptor {
    const FIELD_SIZE: usize = <u16 as FromFieldRepr>::FIELD_SIZE
        + <[u8; 32] as FromFieldRepr>::FIELD_SIZE
        + <u64 as FromFieldRepr>::FIELD_SIZE
        + <AuthorizationState as FromFieldRepr>::FIELD_SIZE
        + <SignerRole as FromFieldRepr>::FIELD_SIZE
        + <VerificationMethodRef as FromFieldRepr>::FIELD_SIZE
        + midnight_compact_runtime::JUBJUB_POINT_FIELD_SIZE
        + <u64 as FromFieldRepr>::FIELD_SIZE
        + <VerificationRelationship as FromFieldRepr>::FIELD_SIZE
        + <[u8; 32] as FromFieldRepr>::FIELD_SIZE
        + <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let version =
            <u16 as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <u16 as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <u16 as FromFieldRepr>::FIELD_SIZE;
        let authorizationId = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let decisionSequence =
            <u64 as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <u64 as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <u64 as FromFieldRepr>::FIELD_SIZE;
        let state = <AuthorizationState as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <AuthorizationState as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <AuthorizationState as FromFieldRepr>::FIELD_SIZE;
        let role = <SignerRole as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <SignerRole as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <SignerRole as FromFieldRepr>::FIELD_SIZE;
        let signerVerificationMethodRef = <VerificationMethodRef as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <VerificationMethodRef as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <VerificationMethodRef as FromFieldRepr>::FIELD_SIZE;
        let signerPublicKey = midnight_compact_runtime::jubjub_point_from_field_repr(
            &_repr[_offset.._offset + midnight_compact_runtime::JUBJUB_POINT_FIELD_SIZE],
        )?;
        _offset += midnight_compact_runtime::JUBJUB_POINT_FIELD_SIZE;
        let didStateVersion =
            <u64 as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <u64 as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <u64 as FromFieldRepr>::FIELD_SIZE;
        let verificationRelationship = <VerificationRelationship as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <VerificationRelationship as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <VerificationRelationship as FromFieldRepr>::FIELD_SIZE;
        let scopeCommitment = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let policyCommitment = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(AuthorizedSignerDescriptor {
            version,
            authorizationId,
            decisionSequence,
            state,
            role,
            signerVerificationMethodRef,
            signerPublicKey,
            didStateVersion,
            verificationRelationship,
            scopeCommitment,
            policyCommitment,
        })
    }
}
impl From<AuthorizedSignerDescriptor> for midnight_compact_runtime::Value {
    fn from(s: AuthorizedSignerDescriptor) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.version));
        _v.push(midnight_compact_runtime::Value::from(s.authorizationId));
        _v.push(midnight_compact_runtime::Value::from(s.decisionSequence));
        _v.push(midnight_compact_runtime::Value::from(s.state));
        _v.push(midnight_compact_runtime::Value::from(s.role));
        _v.push(midnight_compact_runtime::Value::from(s.signerVerificationMethodRef));
        _v.push(midnight_compact_runtime::Value::from(s.signerPublicKey));
        _v.push(midnight_compact_runtime::Value::from(s.didStateVersion));
        _v.push(midnight_compact_runtime::Value::from(s.verificationRelationship));
        _v.push(midnight_compact_runtime::Value::from(s.scopeCommitment));
        _v.push(midnight_compact_runtime::Value::from(s.policyCommitment));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for AuthorizedSignerDescriptor {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.version.binary_repr(writer);
        self.authorizationId.binary_repr(writer);
        self.decisionSequence.binary_repr(writer);
        self.state.binary_repr(writer);
        self.role.binary_repr(writer);
        self.signerVerificationMethodRef.binary_repr(writer);
        midnight_compact_runtime::jubjub_point_binary_repr(&self.signerPublicKey, writer);
        self.didStateVersion.binary_repr(writer);
        self.verificationRelationship.binary_repr(writer);
        self.scopeCommitment.binary_repr(writer);
        self.policyCommitment.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.version.binary_len()
            + self.authorizationId.binary_len()
            + self.decisionSequence.binary_len()
            + self.state.binary_len()
            + self.role.binary_len()
            + self.signerVerificationMethodRef.binary_len()
            + midnight_compact_runtime::jubjub_point_binary_len(&self.signerPublicKey)
            + self.didStateVersion.binary_len()
            + self.verificationRelationship.binary_len()
            + self.scopeCommitment.binary_len()
            + self.policyCommitment.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct SignerAuthorizationAuthority {
    pub domainCommitment: [u8; 32],
    pub verificationMethodRef: VerificationMethodRef,
    pub publicKey: JubjubPoint,
}
impl Aligned for SignerAuthorizationAuthority {
    fn alignment() -> Alignment {
        Alignment::concat([
            &<[u8; 32] as Aligned>::alignment(),
            &<VerificationMethodRef as Aligned>::alignment(),
            &<JubjubPoint as Aligned>::alignment(),
        ])
    }
}
impl FieldRepr for SignerAuthorizationAuthority {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.domainCommitment.field_repr(writer);
        self.verificationMethodRef.field_repr(writer);
        midnight_compact_runtime::jubjub_point_field_repr(&self.publicKey, writer);
    }
    fn field_size(&self) -> usize {
        self.domainCommitment.field_size()
            + self.verificationMethodRef.field_size()
            + midnight_compact_runtime::jubjub_point_field_size(&self.publicKey)
    }
}
impl FromFieldRepr for SignerAuthorizationAuthority {
    const FIELD_SIZE: usize = <[u8; 32] as FromFieldRepr>::FIELD_SIZE
        + <VerificationMethodRef as FromFieldRepr>::FIELD_SIZE
        + midnight_compact_runtime::JUBJUB_POINT_FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let domainCommitment = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let verificationMethodRef = <VerificationMethodRef as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <VerificationMethodRef as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <VerificationMethodRef as FromFieldRepr>::FIELD_SIZE;
        let publicKey = midnight_compact_runtime::jubjub_point_from_field_repr(
            &_repr[_offset.._offset + midnight_compact_runtime::JUBJUB_POINT_FIELD_SIZE],
        )?;
        _offset += midnight_compact_runtime::JUBJUB_POINT_FIELD_SIZE;
        let _ = _offset;
        Some(SignerAuthorizationAuthority {
            domainCommitment,
            verificationMethodRef,
            publicKey,
        })
    }
}
impl From<SignerAuthorizationAuthority> for midnight_compact_runtime::Value {
    fn from(s: SignerAuthorizationAuthority) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.domainCommitment));
        _v.push(midnight_compact_runtime::Value::from(s.verificationMethodRef));
        _v.push(midnight_compact_runtime::Value::from(s.publicKey));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for SignerAuthorizationAuthority {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.domainCommitment.binary_repr(writer);
        self.verificationMethodRef.binary_repr(writer);
        midnight_compact_runtime::jubjub_point_binary_repr(&self.publicKey, writer);
    }
    fn binary_len(&self) -> usize {
        self.domainCommitment.binary_len()
            + self.verificationMethodRef.binary_len()
            + midnight_compact_runtime::jubjub_point_binary_len(&self.publicKey)
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct StatusRegistryRef {
    pub registryId: [u8; 32],
    pub authorityVerificationMethodRef: VerificationMethodRef,
}
impl Aligned for StatusRegistryRef {
    fn alignment() -> Alignment {
        Alignment::concat([
            &<[u8; 32] as Aligned>::alignment(),
            &<VerificationMethodRef as Aligned>::alignment(),
        ])
    }
}
impl FieldRepr for StatusRegistryRef {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.registryId.field_repr(writer);
        self.authorityVerificationMethodRef.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.registryId.field_size() + self.authorityVerificationMethodRef.field_size()
    }
}
impl FromFieldRepr for StatusRegistryRef {
    const FIELD_SIZE: usize =
        <[u8; 32] as FromFieldRepr>::FIELD_SIZE + <VerificationMethodRef as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let registryId = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let authorityVerificationMethodRef = <VerificationMethodRef as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <VerificationMethodRef as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <VerificationMethodRef as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(StatusRegistryRef {
            registryId,
            authorityVerificationMethodRef,
        })
    }
}
impl From<StatusRegistryRef> for midnight_compact_runtime::Value {
    fn from(s: StatusRegistryRef) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.registryId));
        _v.push(midnight_compact_runtime::Value::from(s.authorityVerificationMethodRef));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for StatusRegistryRef {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.registryId.binary_repr(writer);
        self.authorityVerificationMethodRef.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.registryId.binary_len() + self.authorityVerificationMethodRef.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct NoStatusBinding {}
impl Aligned for NoStatusBinding {
    fn alignment() -> Alignment {
        Alignment::concat([])
    }
}
impl FieldRepr for NoStatusBinding {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {}
    fn field_size(&self) -> usize {
        0
    }
}
impl FromFieldRepr for NoStatusBinding {
    const FIELD_SIZE: usize = 0;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        let mut _offset = 0usize;
        let _ = _offset;
        Some(NoStatusBinding {})
    }
}
impl From<NoStatusBinding> for midnight_compact_runtime::Value {
    fn from(s: NoStatusBinding) -> midnight_compact_runtime::Value {
        midnight_compact_runtime::Value::concat(core::iter::empty::<&midnight_compact_runtime::Value>())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for NoStatusBinding {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        let _ = writer;
    }
    fn binary_len(&self) -> usize {
        0
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct RegistryBoundStatusBinding {
    pub registryRef: StatusRegistryRef,
    pub statusHandleCommitment: [u8; 32],
}
impl Aligned for RegistryBoundStatusBinding {
    fn alignment() -> Alignment {
        Alignment::concat([
            &<StatusRegistryRef as Aligned>::alignment(),
            &<[u8; 32] as Aligned>::alignment(),
        ])
    }
}
impl FieldRepr for RegistryBoundStatusBinding {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.registryRef.field_repr(writer);
        self.statusHandleCommitment.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.registryRef.field_size() + self.statusHandleCommitment.field_size()
    }
}
impl FromFieldRepr for RegistryBoundStatusBinding {
    const FIELD_SIZE: usize =
        <StatusRegistryRef as FromFieldRepr>::FIELD_SIZE + <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let registryRef = <StatusRegistryRef as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <StatusRegistryRef as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <StatusRegistryRef as FromFieldRepr>::FIELD_SIZE;
        let statusHandleCommitment = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(RegistryBoundStatusBinding {
            registryRef,
            statusHandleCommitment,
        })
    }
}
impl From<RegistryBoundStatusBinding> for midnight_compact_runtime::Value {
    fn from(s: RegistryBoundStatusBinding) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.registryRef));
        _v.push(midnight_compact_runtime::Value::from(s.statusHandleCommitment));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for RegistryBoundStatusBinding {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.registryRef.binary_repr(writer);
        self.statusHandleCommitment.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.registryRef.binary_len() + self.statusHandleCommitment.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct ContractAddress {
    pub bytes: [u8; 32],
}
impl Aligned for ContractAddress {
    fn alignment() -> Alignment {
        Alignment::concat([&<[u8; 32] as Aligned>::alignment()])
    }
}
impl FieldRepr for ContractAddress {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.bytes.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.bytes.field_size()
    }
}
impl FromFieldRepr for ContractAddress {
    const FIELD_SIZE: usize = <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let bytes = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(ContractAddress { bytes })
    }
}
impl From<ContractAddress> for midnight_compact_runtime::Value {
    fn from(s: ContractAddress) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.bytes));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for ContractAddress {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.bytes.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.bytes.binary_len()
    }
}

pub trait Witnesses<PS> {}
impl<PS> Witnesses<PS> for NoWitnesses {}

pub struct Contract<PS, W = NoWitnesses>
where
    W: Witnesses<PS>,
{
    pub witnesses: W,
    _ps: PhantomData<PS>,
}

impl<PS, W> Contract<PS, W>
where
    PS: Clone,
    W: Witnesses<PS>,
{
    pub fn new(witnesses: W) -> Self {
        Self {
            witnesses,
            _ps: PhantomData,
        }
    }
    pub fn initial_state(&self, ctx: ConstructorContext<PS>) -> Result<ConstructorResult<PS>, CompactError> {
        let sv = new_array(vec![]);
        let state = ChargedState::new(sv);
        let qctx = QueryContext::new(state, midnight_compact_runtime::ContractAddress::default());
        let __compact_initial_query_context = qctx.clone();
        let __compact_constructor_id = "constructor";
        let mut __compact_proof_data = PartialProofData::<DefaultDB>::new(aligned_value_from_parts(&[]));
        let __compact_constructor_proof_data = ConstructorProofData::new(
            __compact_constructor_id,
            __compact_initial_query_context,
            qctx.clone(),
            __compact_proof_data.finalize(aligned_value_from_parts(&[])),
        );
        Ok(ConstructorResult {
            current_contract_state: qctx.state,
            current_private_state: ctx.initial_private_state,
            current_zswap_local_state: ctx.empty_zswap_local_state,
            constructor_proof_data: __compact_constructor_proof_data,
        })
    }
}

pub struct Ledger<'a, D: DB = DefaultDB> {
    state: &'a ChargedState<D>,
}

pub fn ledger<D: DB>(state: &ChargedState<D>) -> Ledger<'_, D> {
    Ledger { state }
}

impl<'a, D: DB> Ledger<'a, D> {}

pub mod pure_circuits {
    use super::*;

    pub fn assert_valid_schema_ref(schema: SchemaRef) -> Result<(), CompactError> {
        compact_assert!(
            (schema.packageId
                != [
                    0u8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                ]),
            "Schema package id must be set"
        );
        compact_assert!(
            (schema.schemaId
                != [
                    0u8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                ]),
            "Schema id must be set"
        );
        let t = schema.majorVersion;
        compact_assert!((t > 0), "Schema major version must be positive");
        Ok(())
    }

    pub fn assert_matching_schema_refs(expected: SchemaRef, actual: SchemaRef) -> Result<(), CompactError> {
        pure_circuits::assert_valid_schema_ref(expected.clone())?;
        pure_circuits::assert_valid_schema_ref(actual.clone())?;
        compact_assert!(
            ((((expected.packageId == actual.packageId) && (expected.schemaId == actual.schemaId))
                && (expected.majorVersion == actual.majorVersion))
                && (expected.minorVersion == actual.minorVersion)),
            "Schema reference mismatch"
        );
        Ok(())
    }

    pub fn assert_valid_verification_method_ref(
        verification_method_ref: VerificationMethodRef,
    ) -> Result<(), CompactError> {
        compact_assert!(
            (verification_method_ref.controllerAddress.bytes
                != [
                    0u8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                ]),
            "Verification method controller address must be set"
        );
        compact_assert!(
            (verification_method_ref.methodId
                != [
                    0u8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                ]),
            "Verification method reference must be set"
        );
        Ok(())
    }

    pub(crate) fn assert_matching_jubjub_points(
        expected: JubjubPoint,
        actual: JubjubPoint,
    ) -> Result<(), CompactError> {
        compact_assert!(
            ((midnight_compact_runtime::jubjub_point_x(expected.clone())
                == midnight_compact_runtime::jubjub_point_x(actual.clone()))
                && (midnight_compact_runtime::jubjub_point_y(expected.clone())
                    == midnight_compact_runtime::jubjub_point_y(actual.clone()))),
            "Jubjub points do not match"
        );
        Ok(())
    }

    pub(crate) fn assert_usable_jubjub_point(point: JubjubPoint) -> Result<(), CompactError> {
        compact_assert!(
            ((midnight_compact_runtime::jubjub_point_x(point.clone()) != Fr::from(0u64))
                || (midnight_compact_runtime::jubjub_point_y(point.clone()) != Fr::from(1u64))),
            "Jubjub point must not be the identity point"
        );
        let subgroup_projection = midnight_compact_runtime::ec_mul(
            midnight_compact_runtime::ec_mul(
                point.clone(),
                Fr::from_le_bytes(&[
                    0x97, 0xE5, 0xDE, 0xDA, 0xCB, 0xE1, 0x12, 0x5A, 0x10, 0x02, 0x99, 0x79, 0x12, 0x04, 0xCD, 0x14,
                    0x60, 0x87, 0x26, 0x20, 0x60, 0xE7, 0xCC, 0x20, 0xF5, 0x75, 0xA6, 0x4C, 0x9D, 0xB6, 0xCF, 0x01,
                ])
                .expect("Field literal is canonical"),
            ),
            Fr::from(8u64),
        );
        Ok(pure_circuits::assert_matching_jubjub_points(
            point.clone(),
            subgroup_projection.clone(),
        )?)
    }

    pub fn verify_signature(pk: JubjubPoint, signature: Signature, challenge: Fr) -> Result<bool, CompactError> {
        pure_circuits::assert_usable_jubjub_point(pk.clone())?;
        pure_circuits::assert_usable_jubjub_point(signature.r.clone())?;
        let left_side = midnight_compact_runtime::ec_mul_generator(signature.s.clone());
        let c_pk = midnight_compact_runtime::ec_mul(pk.clone(), challenge);
        let right_side = midnight_compact_runtime::ec_add(signature.r.clone(), c_pk.clone());
        let x_matches = (midnight_compact_runtime::jubjub_point_x(left_side.clone())
            == midnight_compact_runtime::jubjub_point_x(right_side.clone()));
        let y_matches = (midnight_compact_runtime::jubjub_point_y(left_side.clone())
            == midnight_compact_runtime::jubjub_point_y(right_side.clone()));
        compact_assert!((x_matches && y_matches), "Signature verification failed");
        Ok((x_matches && y_matches))
    }

    pub fn issuance_context_tag() -> Result<[u8; 32], CompactError> {
        Ok([
            109u8, 105, 100, 110, 105, 103, 104, 116, 58, 118, 99, 58, 105, 115, 115, 117, 97, 110, 99, 101, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0,
        ])
    }

    pub fn presentation_context_tag() -> Result<[u8; 32], CompactError> {
        Ok([
            109u8, 105, 100, 110, 105, 103, 104, 116, 58, 118, 99, 58, 112, 114, 101, 115, 101, 110, 116, 97, 116, 105,
            111, 110, 0, 0, 0, 0, 0, 0, 0, 0,
        ])
    }

    pub fn signer_authorization_context_tag() -> Result<[u8; 32], CompactError> {
        Ok([
            109u8, 105, 100, 110, 105, 103, 104, 116, 58, 118, 99, 58, 115, 105, 103, 110, 101, 114, 45, 97, 117, 116,
            104, 58, 118, 49, 0, 0, 0, 0, 0, 0,
        ])
    }

    pub fn verifier_request_context_tag() -> Result<[u8; 32], CompactError> {
        Ok([
            109u8, 105, 100, 110, 105, 103, 104, 116, 58, 118, 99, 58, 118, 101, 114, 105, 102, 105, 101, 114, 45, 114,
            101, 113, 58, 118, 49, 0, 0, 0, 0, 0,
        ])
    }

    pub(crate) fn proof_payload_root_for_context(
        body_root: [u8; 32],
        context_tag: [u8; 32],
        proof: Proof,
    ) -> Result<[u8; 32], CompactError> {
        Ok(midnight_compact_runtime::std_lib::persistent_hash_aligned(&[
            midnight_compact_runtime::AlignedValue::from(body_root),
            midnight_compact_runtime::AlignedValue::from(context_tag),
            midnight_compact_runtime::AlignedValue::from(midnight_compact_runtime::std_lib::persistent_hash_aligned(
                &[midnight_compact_runtime::AlignedValue::from(
                    proof.signerVerificationMethodRef,
                )],
            )),
            midnight_compact_runtime::AlignedValue::from(midnight_compact_runtime::upgrade_from_transient(
                midnight_compact_runtime::std_lib::transient_hash_aligned(&[
                    midnight_compact_runtime::AlignedValue::from(proof.createdAt),
                ]),
            )),
            midnight_compact_runtime::AlignedValue::from(proof.challengeHash),
        ]))
    }

    pub(crate) fn proof_challenge_for_context(
        body_root: [u8; 32],
        context_tag: [u8; 32],
        proof: Proof,
    ) -> Result<Fr, CompactError> {
        Ok(midnight_compact_runtime::degrade_to_transient(
            midnight_compact_runtime::std_lib::persistent_hash_aligned(&[
                midnight_compact_runtime::AlignedValue::from(pure_circuits::proof_payload_root_for_context(
                    body_root,
                    context_tag,
                    proof.clone(),
                )?),
                midnight_compact_runtime::AlignedValue::from(midnight_compact_runtime::upgrade_from_transient(
                    midnight_compact_runtime::std_lib::transient_hash_aligned(&[
                        midnight_compact_runtime::AlignedValue::from(proof.publicKey),
                    ]),
                )),
                midnight_compact_runtime::AlignedValue::from(midnight_compact_runtime::upgrade_from_transient(
                    midnight_compact_runtime::std_lib::transient_hash_aligned(&[
                        midnight_compact_runtime::AlignedValue::from(proof.signature.r),
                    ]),
                )),
            ]),
        ))
    }

    pub(crate) fn assert_valid_proof_for_context(
        body_root: [u8; 32],
        context_tag: [u8; 32],
        proof: Proof,
    ) -> Result<(), CompactError> {
        pure_circuits::assert_valid_verification_method_ref(proof.signerVerificationMethodRef.clone())?;
        compact_assert!(
            pure_circuits::verify_signature(
                proof.publicKey.clone(),
                proof.signature.clone(),
                pure_circuits::proof_challenge_for_context(body_root, context_tag, proof.clone())?
            )?,
            "Proof verification failed"
        );
        Ok(())
    }

    pub fn issuance_proof_payload_root(body_root: [u8; 32], proof: Proof) -> Result<[u8; 32], CompactError> {
        Ok(pure_circuits::proof_payload_root_for_context(
            body_root,
            pure_circuits::issuance_context_tag()?,
            proof.clone(),
        )?)
    }

    pub fn presentation_proof_payload_root(body_root: [u8; 32], proof: Proof) -> Result<[u8; 32], CompactError> {
        Ok(pure_circuits::proof_payload_root_for_context(
            body_root,
            pure_circuits::presentation_context_tag()?,
            proof.clone(),
        )?)
    }

    pub fn issuance_proof_challenge(body_root: [u8; 32], proof: Proof) -> Result<Fr, CompactError> {
        Ok(pure_circuits::proof_challenge_for_context(
            body_root,
            pure_circuits::issuance_context_tag()?,
            proof.clone(),
        )?)
    }

    pub fn presentation_proof_challenge(body_root: [u8; 32], proof: Proof) -> Result<Fr, CompactError> {
        Ok(pure_circuits::proof_challenge_for_context(
            body_root,
            pure_circuits::presentation_context_tag()?,
            proof.clone(),
        )?)
    }

    pub fn signer_authorization_proof_challenge(body_root: [u8; 32], proof: Proof) -> Result<Fr, CompactError> {
        Ok(pure_circuits::proof_challenge_for_context(
            body_root,
            pure_circuits::signer_authorization_context_tag()?,
            proof.clone(),
        )?)
    }

    pub fn verifier_request_proof_challenge(
        request_scope_commitment: [u8; 32],
        proof: Proof,
    ) -> Result<Fr, CompactError> {
        Ok(pure_circuits::proof_challenge_for_context(
            request_scope_commitment,
            pure_circuits::verifier_request_context_tag()?,
            proof.clone(),
        )?)
    }

    pub fn assert_valid_issuance_context_proof(body_root: [u8; 32], proof: Proof) -> Result<(), CompactError> {
        Ok(pure_circuits::assert_valid_proof_for_context(
            body_root,
            pure_circuits::issuance_context_tag()?,
            proof.clone(),
        )?)
    }

    pub fn assert_valid_presentation_context_proof(body_root: [u8; 32], proof: Proof) -> Result<(), CompactError> {
        Ok(pure_circuits::assert_valid_proof_for_context(
            body_root,
            pure_circuits::presentation_context_tag()?,
            proof.clone(),
        )?)
    }

    pub fn assert_valid_signer_authorization_context_proof(
        body_root: [u8; 32],
        proof: Proof,
    ) -> Result<(), CompactError> {
        Ok(pure_circuits::assert_valid_proof_for_context(
            body_root,
            pure_circuits::signer_authorization_context_tag()?,
            proof.clone(),
        )?)
    }

    pub fn assert_valid_verifier_request_context_proof(
        request_scope_commitment: [u8; 32],
        proof: Proof,
    ) -> Result<(), CompactError> {
        Ok(pure_circuits::assert_valid_proof_for_context(
            request_scope_commitment,
            pure_circuits::verifier_request_context_tag()?,
            proof.clone(),
        )?)
    }

    pub fn assert_valid_authorized_signer_descriptor(
        descriptor: AuthorizedSignerDescriptor,
    ) -> Result<(), CompactError> {
        compact_assert!((descriptor.version == 1), "Signer authorization version mismatch");
        compact_assert!(
            (descriptor.authorizationId
                != [
                    0u8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                ]),
            "Signer authorization id must be set"
        );
        let t = descriptor.decisionSequence;
        compact_assert!((t > 0), "Signer authorization decision sequence must be positive");
        pure_circuits::assert_valid_verification_method_ref(descriptor.signerVerificationMethodRef.clone())?;
        pure_circuits::assert_usable_jubjub_point(descriptor.signerPublicKey.clone())?;
        let t_0 = descriptor.didStateVersion;
        compact_assert!((t_0 > 0), "Signer authorization DID state version must be positive");
        compact_assert!(
            (descriptor.scopeCommitment
                != [
                    0u8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                ]),
            "Signer authorization scope commitment must be set"
        );
        compact_assert!(
            (descriptor.policyCommitment
                != [
                    0u8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                ]),
            "Signer authorization policy commitment must be set"
        );
        Ok(if (descriptor.role == SignerRole::issuer) {
            compact_assert!(
                (descriptor.verificationRelationship == VerificationRelationship::assertionMethod),
                "Issuer authorization requires assertionMethod"
            );
        } else {
            compact_assert!(
                ((descriptor.verificationRelationship == VerificationRelationship::authentication)
                    || (descriptor.verificationRelationship == VerificationRelationship::capabilityInvocation)),
                "Verifier authorization requires authentication or capabilityInvocation"
            );
        })
    }

    pub fn authorized_signer_descriptor_root(descriptor: AuthorizedSignerDescriptor) -> Result<[u8; 32], CompactError> {
        pure_circuits::assert_valid_authorized_signer_descriptor(descriptor.clone())?;
        Ok(pure_circuits::authorized_signer_descriptor_hash(descriptor.clone())?)
    }

    pub(crate) fn authorized_signer_descriptor_hash(
        descriptor: AuthorizedSignerDescriptor,
    ) -> Result<[u8; 32], CompactError> {
        Ok(midnight_compact_runtime::std_lib::persistent_hash_aligned(&[
            midnight_compact_runtime::AlignedValue::from(descriptor),
        ]))
    }

    pub fn issuer_scope_commitment(schema: SchemaRef) -> Result<[u8; 32], CompactError> {
        pure_circuits::assert_valid_schema_ref(schema.clone())?;
        Ok(midnight_compact_runtime::std_lib::persistent_hash_aligned(&[
            midnight_compact_runtime::AlignedValue::from(schema),
        ]))
    }

    pub fn assert_proof_signer_matches_authorization(
        proof: Proof,
        descriptor: AuthorizedSignerDescriptor,
    ) -> Result<(), CompactError> {
        pure_circuits::assert_valid_authorized_signer_descriptor(descriptor.clone())?;
        compact_assert!(
            (descriptor.state == AuthorizationState::active),
            "Signer authorization must be active"
        );
        compact_assert!(
            (proof.signerVerificationMethodRef.controllerAddress
                == descriptor.signerVerificationMethodRef.controllerAddress),
            "Proof signer controller does not match authorization"
        );
        compact_assert!(
            (proof.signerVerificationMethodRef.methodId == descriptor.signerVerificationMethodRef.methodId),
            "Proof signer method does not match authorization"
        );
        Ok(pure_circuits::assert_matching_jubjub_points(
            descriptor.signerPublicKey.clone(),
            proof.publicKey.clone(),
        )?)
    }

    pub fn assert_authorized_issuer_descriptor(
        schema: SchemaRef,
        proof: Proof,
        descriptor: AuthorizedSignerDescriptor,
    ) -> Result<(), CompactError> {
        pure_circuits::assert_proof_signer_matches_authorization(proof.clone(), descriptor.clone())?;
        compact_assert!(
            (descriptor.role == SignerRole::issuer),
            "Signer authorization role must be issuer"
        );
        compact_assert!(
            (descriptor.scopeCommitment == pure_circuits::issuer_scope_commitment(schema.clone())?),
            "Issuer authorization scope does not match schema"
        );
        Ok(())
    }

    pub fn assert_authorized_verifier_proof(
        request_scope_commitment: [u8; 32],
        proof: Proof,
        descriptor: AuthorizedSignerDescriptor,
    ) -> Result<(), CompactError> {
        compact_assert!(
            (request_scope_commitment
                != [
                    0u8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                ]),
            "Verifier request scope commitment must be set"
        );
        pure_circuits::assert_proof_signer_matches_authorization(proof.clone(), descriptor.clone())?;
        compact_assert!(
            (descriptor.role == SignerRole::verifier),
            "Signer authorization role must be verifier"
        );
        compact_assert!(
            (descriptor.scopeCommitment == request_scope_commitment),
            "Verifier authorization scope does not match request"
        );
        Ok(pure_circuits::assert_valid_verifier_request_context_proof(
            request_scope_commitment,
            proof.clone(),
        )?)
    }

    pub fn assert_valid_signer_authorization_authority(
        authority: SignerAuthorizationAuthority,
    ) -> Result<(), CompactError> {
        compact_assert!(
            (authority.domainCommitment
                != [
                    0u8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                ]),
            "Signer authorization authority domain must be set"
        );
        pure_circuits::assert_valid_verification_method_ref(authority.verificationMethodRef.clone())?;
        Ok(pure_circuits::assert_usable_jubjub_point(authority.publicKey.clone())?)
    }

    pub fn signer_authorization_decision_root(
        descriptor: AuthorizedSignerDescriptor,
        domain_commitment: [u8; 32],
    ) -> Result<[u8; 32], CompactError> {
        pure_circuits::assert_valid_authorized_signer_descriptor(descriptor.clone())?;
        compact_assert!(
            (domain_commitment
                != [
                    0u8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                ]),
            "Signer authorization authority domain must be set"
        );
        Ok(midnight_compact_runtime::std_lib::persistent_hash_aligned(&[
            midnight_compact_runtime::AlignedValue::from(domain_commitment),
            midnight_compact_runtime::AlignedValue::from(pure_circuits::authorized_signer_descriptor_hash(
                descriptor.clone(),
            )?),
        ]))
    }

    pub fn assert_valid_signer_authorization_proof(
        descriptor: AuthorizedSignerDescriptor,
        authorization_proof: Proof,
        authority: SignerAuthorizationAuthority,
    ) -> Result<(), CompactError> {
        pure_circuits::assert_valid_authorized_signer_descriptor(descriptor.clone())?;
        pure_circuits::assert_valid_signer_authorization_authority(authority.clone())?;
        compact_assert!(
            (authorization_proof.createdAt == descriptor.decisionSequence),
            "Authorization proof sequence does not match descriptor"
        );
        compact_assert!(
            (authorization_proof.signerVerificationMethodRef.controllerAddress
                == authority.verificationMethodRef.controllerAddress),
            "Authorization proof controller does not match authority"
        );
        compact_assert!(
            (authorization_proof.signerVerificationMethodRef.methodId == authority.verificationMethodRef.methodId),
            "Authorization proof method does not match authority"
        );
        pure_circuits::assert_matching_jubjub_points(
            authority.publicKey.clone(),
            authorization_proof.publicKey.clone(),
        )?;
        Ok(pure_circuits::assert_valid_signer_authorization_context_proof(
            pure_circuits::signer_authorization_decision_root(descriptor.clone(), authority.domainCommitment.clone())?,
            authorization_proof.clone(),
        )?)
    }

    pub fn assert_valid_signer_authorization_update(
        previous: AuthorizedSignerDescriptor,
        next: AuthorizedSignerDescriptor,
    ) -> Result<(), CompactError> {
        pure_circuits::assert_valid_authorized_signer_descriptor(previous.clone())?;
        pure_circuits::assert_valid_authorized_signer_descriptor(next.clone())?;
        compact_assert!(
            (previous.authorizationId == next.authorizationId),
            "Signer authorization update id mismatch"
        );
        let t = next.decisionSequence;
        compact_assert!(
            (t > previous.decisionSequence),
            "Signer authorization update sequence must increase"
        );
        let t_0 = next.didStateVersion;
        compact_assert!(
            (t_0 >= previous.didStateVersion),
            "Signer authorization DID state version must not decrease"
        );
        compact_assert!(
            ((previous.state != AuthorizationState::revoked) || (next.state == AuthorizationState::revoked)),
            "Revoked signer authorization must remain revoked"
        );
        Ok(())
    }

    pub fn assert_valid_explicit_holder_binding(binding: ExplicitHolderBinding) -> Result<(), CompactError> {
        Ok(pure_circuits::assert_valid_verification_method_ref(
            binding.holderVerificationMethodRef.clone(),
        )?)
    }

    pub fn assert_matching_explicit_holder_bindings(
        credential_binding: ExplicitHolderBinding,
        presentation_binding: ExplicitHolderBinding,
    ) -> Result<(), CompactError> {
        pure_circuits::assert_valid_explicit_holder_binding(credential_binding.clone())?;
        pure_circuits::assert_valid_explicit_holder_binding(presentation_binding.clone())?;
        compact_assert!(
            (presentation_binding.holderVerificationMethodRef.controllerAddress
                == credential_binding.holderVerificationMethodRef.controllerAddress),
            "Presentation holder controller does not match credential holder binding"
        );
        compact_assert!(
            (presentation_binding.holderVerificationMethodRef.methodId
                == credential_binding.holderVerificationMethodRef.methodId),
            "Presentation holder method reference does not match credential holder binding"
        );
        Ok(())
    }

    pub fn assert_proof_matches_explicit_holder_binding(
        binding: ExplicitHolderBinding,
        presentation_proof: Proof,
    ) -> Result<(), CompactError> {
        pure_circuits::assert_valid_explicit_holder_binding(binding.clone())?;
        pure_circuits::assert_valid_verification_method_ref(presentation_proof.signerVerificationMethodRef.clone())?;
        compact_assert!(
            (binding.holderVerificationMethodRef.controllerAddress
                == presentation_proof.signerVerificationMethodRef.controllerAddress),
            "Presentation proof signer must match holder binding"
        );
        compact_assert!(
            (binding.holderVerificationMethodRef.methodId == presentation_proof.signerVerificationMethodRef.methodId),
            "Presentation proof signer method reference must match holder binding"
        );
        Ok(())
    }

    pub fn assert_valid_status_registry_ref(registry_ref: StatusRegistryRef) -> Result<(), CompactError> {
        compact_assert!(
            (registry_ref.registryId
                != [
                    0u8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                ]),
            "Status registry id must be set"
        );
        Ok(pure_circuits::assert_valid_verification_method_ref(
            registry_ref.authorityVerificationMethodRef.clone(),
        )?)
    }

    pub fn assert_valid_registry_bound_status_binding(binding: RegistryBoundStatusBinding) -> Result<(), CompactError> {
        pure_circuits::assert_valid_status_registry_ref(binding.registryRef.clone())?;
        compact_assert!(
            (binding.statusHandleCommitment
                != [
                    0u8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                ]),
            "Status handle commitment must be set"
        );
        Ok(())
    }

    pub fn registry_bound_status_binding_root(binding: RegistryBoundStatusBinding) -> Result<[u8; 32], CompactError> {
        pure_circuits::assert_valid_registry_bound_status_binding(binding.clone())?;
        Ok(midnight_compact_runtime::std_lib::persistent_hash_aligned(&[
            midnight_compact_runtime::AlignedValue::from(binding),
        ]))
    }
}
