//! GENERATED — do not edit; run `just codegen-vc`.
//!
//! Source: `packages/core/primitives/iso-registry/src/iso-registry.compact`
//! in the pinned `third_party/midnight-verifiable-credentials` submodule.
// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit by hand.

#![allow(
    clippy::all,
    dead_code,
    unused_imports,
    unused_variables,
    unused_parens,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals
)]

use std::marker::PhantomData;

use compact_runtime::*;

compact_runtime::check_runtime_version!("0.16.100");

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct CountryCode {
    pub value: u16,
}
impl Aligned for CountryCode {
    fn alignment() -> Alignment {
        Alignment::concat([&<u16 as Aligned>::alignment()])
    }
}
impl FieldRepr for CountryCode {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.value.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.value.field_size()
    }
}
impl FromFieldRepr for CountryCode {
    const FIELD_SIZE: usize = <u16 as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let value =
            <u16 as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <u16 as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <u16 as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(CountryCode { value })
    }
}
impl From<CountryCode> for compact_runtime::Value {
    fn from(s: CountryCode) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.value));
        compact_runtime::Value::concat(_v.iter())
    }
}
impl compact_runtime::BinaryHashRepr for CountryCode {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.value.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.value.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct CurrencyCode {
    pub value: u16,
}
impl Aligned for CurrencyCode {
    fn alignment() -> Alignment {
        Alignment::concat([&<u16 as Aligned>::alignment()])
    }
}
impl FieldRepr for CurrencyCode {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.value.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.value.field_size()
    }
}
impl FromFieldRepr for CurrencyCode {
    const FIELD_SIZE: usize = <u16 as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let value =
            <u16 as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <u16 as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <u16 as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(CurrencyCode { value })
    }
}
impl From<CurrencyCode> for compact_runtime::Value {
    fn from(s: CurrencyCode) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.value));
        compact_runtime::Value::concat(_v.iter())
    }
}
impl compact_runtime::BinaryHashRepr for CurrencyCode {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.value.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.value.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct LanguageCode {
    pub value: u16,
}
impl Aligned for LanguageCode {
    fn alignment() -> Alignment {
        Alignment::concat([&<u16 as Aligned>::alignment()])
    }
}
impl FieldRepr for LanguageCode {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.value.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.value.field_size()
    }
}
impl FromFieldRepr for LanguageCode {
    const FIELD_SIZE: usize = <u16 as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let value =
            <u16 as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <u16 as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <u16 as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(LanguageCode { value })
    }
}
impl From<LanguageCode> for compact_runtime::Value {
    fn from(s: LanguageCode) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.value));
        compact_runtime::Value::concat(_v.iter())
    }
}
impl compact_runtime::BinaryHashRepr for LanguageCode {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.value.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.value.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct RegionCode {
    pub country: u16,
    pub subdivision: u16,
}
impl Aligned for RegionCode {
    fn alignment() -> Alignment {
        Alignment::concat([&<u16 as Aligned>::alignment(), &<u16 as Aligned>::alignment()])
    }
}
impl FieldRepr for RegionCode {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.country.field_repr(writer);
        self.subdivision.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.country.field_size() + self.subdivision.field_size()
    }
}
impl FromFieldRepr for RegionCode {
    const FIELD_SIZE: usize = <u16 as FromFieldRepr>::FIELD_SIZE + <u16 as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let country =
            <u16 as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <u16 as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <u16 as FromFieldRepr>::FIELD_SIZE;
        let subdivision =
            <u16 as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <u16 as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <u16 as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(RegionCode { country, subdivision })
    }
}
impl From<RegionCode> for compact_runtime::Value {
    fn from(s: RegionCode) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.country));
        _v.push(compact_runtime::Value::from(s.subdivision));
        compact_runtime::Value::concat(_v.iter())
    }
}
impl compact_runtime::BinaryHashRepr for RegionCode {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.country.binary_repr(writer);
        self.subdivision.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.country.binary_len() + self.subdivision.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct GenderCode {
    pub value: u8,
}
impl Aligned for GenderCode {
    fn alignment() -> Alignment {
        Alignment::concat([&<u8 as Aligned>::alignment()])
    }
}
impl FieldRepr for GenderCode {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.value.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.value.field_size()
    }
}
impl FromFieldRepr for GenderCode {
    const FIELD_SIZE: usize = <u8 as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let value =
            <u8 as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <u8 as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <u8 as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(GenderCode { value })
    }
}
impl From<GenderCode> for compact_runtime::Value {
    fn from(s: GenderCode) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.value));
        compact_runtime::Value::concat(_v.iter())
    }
}
impl compact_runtime::BinaryHashRepr for GenderCode {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.value.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.value.binary_len()
    }
}

pub trait Witnesses<PS> {}
impl<PS> Witnesses<PS> for NoWitnesses {}

pub struct Contract<PS, W = NoWitnesses>
where
    W: Witnesses<PS>,
{
    pub witnesses: W,
    _ps: PhantomData<PS>,
}

impl<PS, W> Contract<PS, W>
where
    PS: Clone,
    W: Witnesses<PS>,
{
    pub fn new(witnesses: W) -> Self {
        Self {
            witnesses,
            _ps: PhantomData,
        }
    }
    pub fn initial_state(&self, ctx: ConstructorContext<PS>) -> Result<ConstructorResult<PS>, CompactError> {
        let sv = new_array(vec![]);
        let state = ChargedState::new(sv);
        let qctx = QueryContext::new(state, compact_runtime::ContractAddress::default());
        Ok(ConstructorResult {
            current_contract_state: qctx.state,
            current_private_state: ctx.initial_private_state,
            current_zswap_local_state: ctx.empty_zswap_local_state,
        })
    }
}

pub struct Ledger<'a, D: DB = DefaultDB> {
    state: &'a ChargedState<D>,
}

pub fn ledger<D: DB>(state: &ChargedState<D>) -> Ledger<'_, D> {
    Ledger { state }
}

impl<'a, D: DB> Ledger<'a, D> {}

pub mod pure_circuits {
    use super::*;

    pub fn assert_country_equals(actual: CountryCode, expected: u16) -> Result<(), CompactError> {
        compact_assert!((actual.value == expected), "Country code does not match expected value");
        Ok(())
    }

    pub fn assert_region_country_equals(region: RegionCode, expected_country: u16) -> Result<(), CompactError> {
        compact_assert!(
            (region.country == expected_country),
            "Region country does not match expected value"
        );
        Ok(())
    }
}
