//! GENERATED — do not edit; run `just codegen-vc`.
//!
//! Source: `packages/core/capabilities/same-holder/src/same-holder.compact`
//! in the pinned `third_party/midnight-verifiable-credentials` submodule.
// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit by hand.

#![allow(
    clippy::all,
    dead_code,
    unused_imports,
    unused_variables,
    unused_parens,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals
)]

use std::marker::PhantomData;

use midnight_compact_runtime::*;

midnight_compact_runtime::check_runtime_version!("0.16.100");

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct SchemaRef {
    pub packageId: [u8; 32],
    pub schemaId: [u8; 32],
    pub majorVersion: u16,
    pub minorVersion: u16,
}
impl Aligned for SchemaRef {
    fn alignment() -> Alignment {
        Alignment::concat([
            &<[u8; 32] as Aligned>::alignment(),
            &<[u8; 32] as Aligned>::alignment(),
            &<u16 as Aligned>::alignment(),
            &<u16 as Aligned>::alignment(),
        ])
    }
}
impl FieldRepr for SchemaRef {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.packageId.field_repr(writer);
        self.schemaId.field_repr(writer);
        self.majorVersion.field_repr(writer);
        self.minorVersion.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.packageId.field_size()
            + self.schemaId.field_size()
            + self.majorVersion.field_size()
            + self.minorVersion.field_size()
    }
}
impl FromFieldRepr for SchemaRef {
    const FIELD_SIZE: usize = <[u8; 32] as FromFieldRepr>::FIELD_SIZE
        + <[u8; 32] as FromFieldRepr>::FIELD_SIZE
        + <u16 as FromFieldRepr>::FIELD_SIZE
        + <u16 as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let packageId = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let schemaId = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let majorVersion =
            <u16 as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <u16 as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <u16 as FromFieldRepr>::FIELD_SIZE;
        let minorVersion =
            <u16 as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <u16 as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <u16 as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(SchemaRef {
            packageId,
            schemaId,
            majorVersion,
            minorVersion,
        })
    }
}
impl From<SchemaRef> for midnight_compact_runtime::Value {
    fn from(s: SchemaRef) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.packageId));
        _v.push(midnight_compact_runtime::Value::from(s.schemaId));
        _v.push(midnight_compact_runtime::Value::from(s.majorVersion));
        _v.push(midnight_compact_runtime::Value::from(s.minorVersion));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for SchemaRef {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.packageId.binary_repr(writer);
        self.schemaId.binary_repr(writer);
        self.majorVersion.binary_repr(writer);
        self.minorVersion.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.packageId.binary_len()
            + self.schemaId.binary_len()
            + self.majorVersion.binary_len()
            + self.minorVersion.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct SchemaCapabilities {
    pub supportsSelectiveDisclosure: bool,
    pub supportsPredicateProofs: bool,
    pub supportsVerifierScopedPseudonym: bool,
    pub supportsSameHolderProof: bool,
}
impl Aligned for SchemaCapabilities {
    fn alignment() -> Alignment {
        Alignment::concat([
            &<bool as Aligned>::alignment(),
            &<bool as Aligned>::alignment(),
            &<bool as Aligned>::alignment(),
            &<bool as Aligned>::alignment(),
        ])
    }
}
impl FieldRepr for SchemaCapabilities {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.supportsSelectiveDisclosure.field_repr(writer);
        self.supportsPredicateProofs.field_repr(writer);
        self.supportsVerifierScopedPseudonym.field_repr(writer);
        self.supportsSameHolderProof.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.supportsSelectiveDisclosure.field_size()
            + self.supportsPredicateProofs.field_size()
            + self.supportsVerifierScopedPseudonym.field_size()
            + self.supportsSameHolderProof.field_size()
    }
}
impl FromFieldRepr for SchemaCapabilities {
    const FIELD_SIZE: usize = <bool as FromFieldRepr>::FIELD_SIZE
        + <bool as FromFieldRepr>::FIELD_SIZE
        + <bool as FromFieldRepr>::FIELD_SIZE
        + <bool as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let supportsSelectiveDisclosure =
            <bool as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <bool as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <bool as FromFieldRepr>::FIELD_SIZE;
        let supportsPredicateProofs =
            <bool as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <bool as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <bool as FromFieldRepr>::FIELD_SIZE;
        let supportsVerifierScopedPseudonym =
            <bool as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <bool as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <bool as FromFieldRepr>::FIELD_SIZE;
        let supportsSameHolderProof =
            <bool as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <bool as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <bool as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(SchemaCapabilities {
            supportsSelectiveDisclosure,
            supportsPredicateProofs,
            supportsVerifierScopedPseudonym,
            supportsSameHolderProof,
        })
    }
}
impl From<SchemaCapabilities> for midnight_compact_runtime::Value {
    fn from(s: SchemaCapabilities) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.supportsSelectiveDisclosure));
        _v.push(midnight_compact_runtime::Value::from(s.supportsPredicateProofs));
        _v.push(midnight_compact_runtime::Value::from(s.supportsVerifierScopedPseudonym));
        _v.push(midnight_compact_runtime::Value::from(s.supportsSameHolderProof));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for SchemaCapabilities {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.supportsSelectiveDisclosure.binary_repr(writer);
        self.supportsPredicateProofs.binary_repr(writer);
        self.supportsVerifierScopedPseudonym.binary_repr(writer);
        self.supportsSameHolderProof.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.supportsSelectiveDisclosure.binary_len()
            + self.supportsPredicateProofs.binary_len()
            + self.supportsVerifierScopedPseudonym.binary_len()
            + self.supportsSameHolderProof.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct SchemaFamilyResolutionHint {
    pub hasResolverHint: bool,
    pub resolverHint: [u8; 32],
}
impl Aligned for SchemaFamilyResolutionHint {
    fn alignment() -> Alignment {
        Alignment::concat([&<bool as Aligned>::alignment(), &<[u8; 32] as Aligned>::alignment()])
    }
}
impl FieldRepr for SchemaFamilyResolutionHint {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.hasResolverHint.field_repr(writer);
        self.resolverHint.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.hasResolverHint.field_size() + self.resolverHint.field_size()
    }
}
impl FromFieldRepr for SchemaFamilyResolutionHint {
    const FIELD_SIZE: usize = <bool as FromFieldRepr>::FIELD_SIZE + <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let hasResolverHint =
            <bool as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <bool as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <bool as FromFieldRepr>::FIELD_SIZE;
        let resolverHint = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(SchemaFamilyResolutionHint {
            hasResolverHint,
            resolverHint,
        })
    }
}
impl From<SchemaFamilyResolutionHint> for midnight_compact_runtime::Value {
    fn from(s: SchemaFamilyResolutionHint) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.hasResolverHint));
        _v.push(midnight_compact_runtime::Value::from(s.resolverHint));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for SchemaFamilyResolutionHint {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.hasResolverHint.binary_repr(writer);
        self.resolverHint.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.hasResolverHint.binary_len() + self.resolverHint.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct SchemaDescriptor {
    pub schema: SchemaRef,
    pub capabilities: SchemaCapabilities,
    pub familyResolutionHint: SchemaFamilyResolutionHint,
}
impl Aligned for SchemaDescriptor {
    fn alignment() -> Alignment {
        Alignment::concat([
            &<SchemaRef as Aligned>::alignment(),
            &<SchemaCapabilities as Aligned>::alignment(),
            &<SchemaFamilyResolutionHint as Aligned>::alignment(),
        ])
    }
}
impl FieldRepr for SchemaDescriptor {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.schema.field_repr(writer);
        self.capabilities.field_repr(writer);
        self.familyResolutionHint.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.schema.field_size() + self.capabilities.field_size() + self.familyResolutionHint.field_size()
    }
}
impl FromFieldRepr for SchemaDescriptor {
    const FIELD_SIZE: usize = <SchemaRef as FromFieldRepr>::FIELD_SIZE
        + <SchemaCapabilities as FromFieldRepr>::FIELD_SIZE
        + <SchemaFamilyResolutionHint as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let schema = <SchemaRef as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <SchemaRef as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <SchemaRef as FromFieldRepr>::FIELD_SIZE;
        let capabilities = <SchemaCapabilities as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <SchemaCapabilities as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <SchemaCapabilities as FromFieldRepr>::FIELD_SIZE;
        let familyResolutionHint = <SchemaFamilyResolutionHint as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <SchemaFamilyResolutionHint as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <SchemaFamilyResolutionHint as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(SchemaDescriptor {
            schema,
            capabilities,
            familyResolutionHint,
        })
    }
}
impl From<SchemaDescriptor> for midnight_compact_runtime::Value {
    fn from(s: SchemaDescriptor) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.schema));
        _v.push(midnight_compact_runtime::Value::from(s.capabilities));
        _v.push(midnight_compact_runtime::Value::from(s.familyResolutionHint));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for SchemaDescriptor {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.schema.binary_repr(writer);
        self.capabilities.binary_repr(writer);
        self.familyResolutionHint.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.schema.binary_len() + self.capabilities.binary_len() + self.familyResolutionHint.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct VerificationMethodRef {
    pub didContractAddress: ContractAddress,
    pub methodId: [u8; 32],
}
impl Aligned for VerificationMethodRef {
    fn alignment() -> Alignment {
        Alignment::concat([
            &<ContractAddress as Aligned>::alignment(),
            &<[u8; 32] as Aligned>::alignment(),
        ])
    }
}
impl FieldRepr for VerificationMethodRef {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.didContractAddress.field_repr(writer);
        self.methodId.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.didContractAddress.field_size() + self.methodId.field_size()
    }
}
impl FromFieldRepr for VerificationMethodRef {
    const FIELD_SIZE: usize = <ContractAddress as FromFieldRepr>::FIELD_SIZE + <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let didContractAddress = <ContractAddress as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <ContractAddress as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <ContractAddress as FromFieldRepr>::FIELD_SIZE;
        let methodId = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(VerificationMethodRef {
            didContractAddress,
            methodId,
        })
    }
}
impl From<VerificationMethodRef> for midnight_compact_runtime::Value {
    fn from(s: VerificationMethodRef) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.didContractAddress));
        _v.push(midnight_compact_runtime::Value::from(s.methodId));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for VerificationMethodRef {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.didContractAddress.binary_repr(writer);
        self.methodId.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.didContractAddress.binary_len() + self.methodId.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct NoPublicClaims {}
impl Aligned for NoPublicClaims {
    fn alignment() -> Alignment {
        Alignment::concat([])
    }
}
impl FieldRepr for NoPublicClaims {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {}
    fn field_size(&self) -> usize {
        0
    }
}
impl FromFieldRepr for NoPublicClaims {
    const FIELD_SIZE: usize = 0;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let _ = _offset;
        Some(NoPublicClaims {})
    }
}
impl From<NoPublicClaims> for midnight_compact_runtime::Value {
    fn from(s: NoPublicClaims) -> midnight_compact_runtime::Value {
        midnight_compact_runtime::Value::concat(core::iter::empty::<&midnight_compact_runtime::Value>())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for NoPublicClaims {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        let _ = writer;
    }
    fn binary_len(&self) -> usize {
        0
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct NoClaimCommitments {}
impl Aligned for NoClaimCommitments {
    fn alignment() -> Alignment {
        Alignment::concat([])
    }
}
impl FieldRepr for NoClaimCommitments {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {}
    fn field_size(&self) -> usize {
        0
    }
}
impl FromFieldRepr for NoClaimCommitments {
    const FIELD_SIZE: usize = 0;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let _ = _offset;
        Some(NoClaimCommitments {})
    }
}
impl From<NoClaimCommitments> for midnight_compact_runtime::Value {
    fn from(s: NoClaimCommitments) -> midnight_compact_runtime::Value {
        midnight_compact_runtime::Value::concat(core::iter::empty::<&midnight_compact_runtime::Value>())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for NoClaimCommitments {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        let _ = writer;
    }
    fn binary_len(&self) -> usize {
        0
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct Signature {
    pub r: JubjubPoint,
    pub s: Fr,
}
impl Aligned for Signature {
    fn alignment() -> Alignment {
        Alignment::concat([&<JubjubPoint as Aligned>::alignment(), &<Fr as Aligned>::alignment()])
    }
}
impl FieldRepr for Signature {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        midnight_compact_runtime::jubjub_point_field_repr(&self.r, writer);
        self.s.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        midnight_compact_runtime::jubjub_point_field_size(&self.r) + self.s.field_size()
    }
}
impl FromFieldRepr for Signature {
    const FIELD_SIZE: usize = midnight_compact_runtime::JUBJUB_POINT_FIELD_SIZE + <Fr as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let r = midnight_compact_runtime::jubjub_point_from_field_repr(
            &_repr[_offset.._offset + midnight_compact_runtime::JUBJUB_POINT_FIELD_SIZE],
        )?;
        _offset += midnight_compact_runtime::JUBJUB_POINT_FIELD_SIZE;
        let s = <Fr as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <Fr as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <Fr as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(Signature { r, s })
    }
}
impl From<Signature> for midnight_compact_runtime::Value {
    fn from(s: Signature) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.r));
        _v.push(midnight_compact_runtime::Value::from(s.s));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for Signature {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        midnight_compact_runtime::jubjub_point_binary_repr(&self.r, writer);
        self.s.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        midnight_compact_runtime::jubjub_point_binary_len(&self.r) + self.s.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct ExplicitHolderBinding {
    pub holderVerificationMethodRef: VerificationMethodRef,
}
impl Aligned for ExplicitHolderBinding {
    fn alignment() -> Alignment {
        Alignment::concat([&<VerificationMethodRef as Aligned>::alignment()])
    }
}
impl FieldRepr for ExplicitHolderBinding {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.holderVerificationMethodRef.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.holderVerificationMethodRef.field_size()
    }
}
impl FromFieldRepr for ExplicitHolderBinding {
    const FIELD_SIZE: usize = <VerificationMethodRef as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let holderVerificationMethodRef = <VerificationMethodRef as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <VerificationMethodRef as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <VerificationMethodRef as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(ExplicitHolderBinding {
            holderVerificationMethodRef,
        })
    }
}
impl From<ExplicitHolderBinding> for midnight_compact_runtime::Value {
    fn from(s: ExplicitHolderBinding) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.holderVerificationMethodRef));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for ExplicitHolderBinding {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.holderVerificationMethodRef.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.holderVerificationMethodRef.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct JubjubHolderBinding {
    pub holderPublicKey: JubjubPoint,
}
impl Aligned for JubjubHolderBinding {
    fn alignment() -> Alignment {
        Alignment::concat([&<JubjubPoint as Aligned>::alignment()])
    }
}
impl FieldRepr for JubjubHolderBinding {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        midnight_compact_runtime::jubjub_point_field_repr(&self.holderPublicKey, writer);
    }
    fn field_size(&self) -> usize {
        midnight_compact_runtime::jubjub_point_field_size(&self.holderPublicKey)
    }
}
impl FromFieldRepr for JubjubHolderBinding {
    const FIELD_SIZE: usize = midnight_compact_runtime::JUBJUB_POINT_FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let holderPublicKey = midnight_compact_runtime::jubjub_point_from_field_repr(
            &_repr[_offset.._offset + midnight_compact_runtime::JUBJUB_POINT_FIELD_SIZE],
        )?;
        _offset += midnight_compact_runtime::JUBJUB_POINT_FIELD_SIZE;
        let _ = _offset;
        Some(JubjubHolderBinding { holderPublicKey })
    }
}
impl From<JubjubHolderBinding> for midnight_compact_runtime::Value {
    fn from(s: JubjubHolderBinding) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.holderPublicKey));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for JubjubHolderBinding {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        midnight_compact_runtime::jubjub_point_binary_repr(&self.holderPublicKey, writer);
    }
    fn binary_len(&self) -> usize {
        midnight_compact_runtime::jubjub_point_binary_len(&self.holderPublicKey)
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct OffchainMidnightHolderBinding {
    pub holderDidStateHash: [u8; 32],
    pub holderMethodId: [u8; 32],
    pub holderPublicKey: JubjubPoint,
}
impl Aligned for OffchainMidnightHolderBinding {
    fn alignment() -> Alignment {
        Alignment::concat([
            &<[u8; 32] as Aligned>::alignment(),
            &<[u8; 32] as Aligned>::alignment(),
            &<JubjubPoint as Aligned>::alignment(),
        ])
    }
}
impl FieldRepr for OffchainMidnightHolderBinding {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.holderDidStateHash.field_repr(writer);
        self.holderMethodId.field_repr(writer);
        midnight_compact_runtime::jubjub_point_field_repr(&self.holderPublicKey, writer);
    }
    fn field_size(&self) -> usize {
        self.holderDidStateHash.field_size()
            + self.holderMethodId.field_size()
            + midnight_compact_runtime::jubjub_point_field_size(&self.holderPublicKey)
    }
}
impl FromFieldRepr for OffchainMidnightHolderBinding {
    const FIELD_SIZE: usize = <[u8; 32] as FromFieldRepr>::FIELD_SIZE
        + <[u8; 32] as FromFieldRepr>::FIELD_SIZE
        + midnight_compact_runtime::JUBJUB_POINT_FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let holderDidStateHash = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let holderMethodId = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let holderPublicKey = midnight_compact_runtime::jubjub_point_from_field_repr(
            &_repr[_offset.._offset + midnight_compact_runtime::JUBJUB_POINT_FIELD_SIZE],
        )?;
        _offset += midnight_compact_runtime::JUBJUB_POINT_FIELD_SIZE;
        let _ = _offset;
        Some(OffchainMidnightHolderBinding {
            holderDidStateHash,
            holderMethodId,
            holderPublicKey,
        })
    }
}
impl From<OffchainMidnightHolderBinding> for midnight_compact_runtime::Value {
    fn from(s: OffchainMidnightHolderBinding) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.holderDidStateHash));
        _v.push(midnight_compact_runtime::Value::from(s.holderMethodId));
        _v.push(midnight_compact_runtime::Value::from(s.holderPublicKey));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for OffchainMidnightHolderBinding {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.holderDidStateHash.binary_repr(writer);
        self.holderMethodId.binary_repr(writer);
        midnight_compact_runtime::jubjub_point_binary_repr(&self.holderPublicKey, writer);
    }
    fn binary_len(&self) -> usize {
        self.holderDidStateHash.binary_len()
            + self.holderMethodId.binary_len()
            + midnight_compact_runtime::jubjub_point_binary_len(&self.holderPublicKey)
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct SecretHolderBinding {
    pub holderSecretCommitment: [u8; 32],
    pub requestChallengeResponse: [u8; 32],
}
impl Aligned for SecretHolderBinding {
    fn alignment() -> Alignment {
        Alignment::concat([&<[u8; 32] as Aligned>::alignment(), &<[u8; 32] as Aligned>::alignment()])
    }
}
impl FieldRepr for SecretHolderBinding {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.holderSecretCommitment.field_repr(writer);
        self.requestChallengeResponse.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.holderSecretCommitment.field_size() + self.requestChallengeResponse.field_size()
    }
}
impl FromFieldRepr for SecretHolderBinding {
    const FIELD_SIZE: usize = <[u8; 32] as FromFieldRepr>::FIELD_SIZE + <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let holderSecretCommitment = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let requestChallengeResponse = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(SecretHolderBinding {
            holderSecretCommitment,
            requestChallengeResponse,
        })
    }
}
impl From<SecretHolderBinding> for midnight_compact_runtime::Value {
    fn from(s: SecretHolderBinding) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.holderSecretCommitment));
        _v.push(midnight_compact_runtime::Value::from(s.requestChallengeResponse));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for SecretHolderBinding {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.holderSecretCommitment.binary_repr(writer);
        self.requestChallengeResponse.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.holderSecretCommitment.binary_len() + self.requestChallengeResponse.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct BlindedSecretHolderBinding {
    pub blindedHolderSecretCommitment: [u8; 32],
    pub issuerNonce: [u8; 32],
    pub requestChallengeResponse: [u8; 32],
}
impl Aligned for BlindedSecretHolderBinding {
    fn alignment() -> Alignment {
        Alignment::concat([
            &<[u8; 32] as Aligned>::alignment(),
            &<[u8; 32] as Aligned>::alignment(),
            &<[u8; 32] as Aligned>::alignment(),
        ])
    }
}
impl FieldRepr for BlindedSecretHolderBinding {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.blindedHolderSecretCommitment.field_repr(writer);
        self.issuerNonce.field_repr(writer);
        self.requestChallengeResponse.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.blindedHolderSecretCommitment.field_size()
            + self.issuerNonce.field_size()
            + self.requestChallengeResponse.field_size()
    }
}
impl FromFieldRepr for BlindedSecretHolderBinding {
    const FIELD_SIZE: usize = <[u8; 32] as FromFieldRepr>::FIELD_SIZE
        + <[u8; 32] as FromFieldRepr>::FIELD_SIZE
        + <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let blindedHolderSecretCommitment = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let issuerNonce = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let requestChallengeResponse = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(BlindedSecretHolderBinding {
            blindedHolderSecretCommitment,
            issuerNonce,
            requestChallengeResponse,
        })
    }
}
impl From<BlindedSecretHolderBinding> for midnight_compact_runtime::Value {
    fn from(s: BlindedSecretHolderBinding) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.blindedHolderSecretCommitment));
        _v.push(midnight_compact_runtime::Value::from(s.issuerNonce));
        _v.push(midnight_compact_runtime::Value::from(s.requestChallengeResponse));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for BlindedSecretHolderBinding {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.blindedHolderSecretCommitment.binary_repr(writer);
        self.issuerNonce.binary_repr(writer);
        self.requestChallengeResponse.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.blindedHolderSecretCommitment.binary_len()
            + self.issuerNonce.binary_len()
            + self.requestChallengeResponse.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct Proof {
    pub signerVerificationMethodRef: VerificationMethodRef,
    pub createdAt: u64,
    pub challengeHash: [u8; 32],
    pub publicKey: JubjubPoint,
    pub signature: Signature,
}
impl Aligned for Proof {
    fn alignment() -> Alignment {
        Alignment::concat([
            &<VerificationMethodRef as Aligned>::alignment(),
            &<u64 as Aligned>::alignment(),
            &<[u8; 32] as Aligned>::alignment(),
            &<JubjubPoint as Aligned>::alignment(),
            &<Signature as Aligned>::alignment(),
        ])
    }
}
impl FieldRepr for Proof {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.signerVerificationMethodRef.field_repr(writer);
        self.createdAt.field_repr(writer);
        self.challengeHash.field_repr(writer);
        midnight_compact_runtime::jubjub_point_field_repr(&self.publicKey, writer);
        self.signature.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.signerVerificationMethodRef.field_size()
            + self.createdAt.field_size()
            + self.challengeHash.field_size()
            + midnight_compact_runtime::jubjub_point_field_size(&self.publicKey)
            + self.signature.field_size()
    }
}
impl FromFieldRepr for Proof {
    const FIELD_SIZE: usize = <VerificationMethodRef as FromFieldRepr>::FIELD_SIZE
        + <u64 as FromFieldRepr>::FIELD_SIZE
        + <[u8; 32] as FromFieldRepr>::FIELD_SIZE
        + midnight_compact_runtime::JUBJUB_POINT_FIELD_SIZE
        + <Signature as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let signerVerificationMethodRef = <VerificationMethodRef as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <VerificationMethodRef as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <VerificationMethodRef as FromFieldRepr>::FIELD_SIZE;
        let createdAt =
            <u64 as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <u64 as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <u64 as FromFieldRepr>::FIELD_SIZE;
        let challengeHash = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let publicKey = midnight_compact_runtime::jubjub_point_from_field_repr(
            &_repr[_offset.._offset + midnight_compact_runtime::JUBJUB_POINT_FIELD_SIZE],
        )?;
        _offset += midnight_compact_runtime::JUBJUB_POINT_FIELD_SIZE;
        let signature = <Signature as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <Signature as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <Signature as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(Proof {
            signerVerificationMethodRef,
            createdAt,
            challengeHash,
            publicKey,
            signature,
        })
    }
}
impl From<Proof> for midnight_compact_runtime::Value {
    fn from(s: Proof) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.signerVerificationMethodRef));
        _v.push(midnight_compact_runtime::Value::from(s.createdAt));
        _v.push(midnight_compact_runtime::Value::from(s.challengeHash));
        _v.push(midnight_compact_runtime::Value::from(s.publicKey));
        _v.push(midnight_compact_runtime::Value::from(s.signature));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for Proof {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.signerVerificationMethodRef.binary_repr(writer);
        self.createdAt.binary_repr(writer);
        self.challengeHash.binary_repr(writer);
        midnight_compact_runtime::jubjub_point_binary_repr(&self.publicKey, writer);
        self.signature.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.signerVerificationMethodRef.binary_len()
            + self.createdAt.binary_len()
            + self.challengeHash.binary_len()
            + midnight_compact_runtime::jubjub_point_binary_len(&self.publicKey)
            + self.signature.binary_len()
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
#[repr(u8)]
pub enum HolderBindingProfile {
    #[default]
    explicitDid = 0,
    secretHolder = 1,
    blindedSecretHolder = 2,
}
impl Aligned for HolderBindingProfile {
    fn alignment() -> Alignment {
        u8::alignment()
    }
}
impl FieldRepr for HolderBindingProfile {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        (*self as u8).field_repr(writer);
    }
    fn field_size(&self) -> usize {
        1
    }
}
impl FromFieldRepr for HolderBindingProfile {
    const FIELD_SIZE: usize = 1;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        let n = u8::from_field_repr(r)?;
        match n {
            0 => Some(Self::explicitDid),
            1 => Some(Self::secretHolder),
            2 => Some(Self::blindedSecretHolder),
            _ => None,
        }
    }
}
impl From<HolderBindingProfile> for midnight_compact_runtime::Value {
    fn from(v: HolderBindingProfile) -> midnight_compact_runtime::Value {
        midnight_compact_runtime::Value::from(v as u8)
    }
}
impl midnight_compact_runtime::BinaryHashRepr for HolderBindingProfile {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        (*self as u8).binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        1
    }
}
#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct CredentialProtocolFeatures {
    pub supportsSelectiveDisclosure: bool,
    pub supportsPredicateProofs: bool,
    pub supportsVerifierScopedPseudonym: bool,
    pub supportsSameHolderProof: bool,
}
impl Aligned for CredentialProtocolFeatures {
    fn alignment() -> Alignment {
        Alignment::concat([
            &<bool as Aligned>::alignment(),
            &<bool as Aligned>::alignment(),
            &<bool as Aligned>::alignment(),
            &<bool as Aligned>::alignment(),
        ])
    }
}
impl FieldRepr for CredentialProtocolFeatures {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.supportsSelectiveDisclosure.field_repr(writer);
        self.supportsPredicateProofs.field_repr(writer);
        self.supportsVerifierScopedPseudonym.field_repr(writer);
        self.supportsSameHolderProof.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.supportsSelectiveDisclosure.field_size()
            + self.supportsPredicateProofs.field_size()
            + self.supportsVerifierScopedPseudonym.field_size()
            + self.supportsSameHolderProof.field_size()
    }
}
impl FromFieldRepr for CredentialProtocolFeatures {
    const FIELD_SIZE: usize = <bool as FromFieldRepr>::FIELD_SIZE
        + <bool as FromFieldRepr>::FIELD_SIZE
        + <bool as FromFieldRepr>::FIELD_SIZE
        + <bool as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let supportsSelectiveDisclosure =
            <bool as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <bool as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <bool as FromFieldRepr>::FIELD_SIZE;
        let supportsPredicateProofs =
            <bool as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <bool as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <bool as FromFieldRepr>::FIELD_SIZE;
        let supportsVerifierScopedPseudonym =
            <bool as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <bool as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <bool as FromFieldRepr>::FIELD_SIZE;
        let supportsSameHolderProof =
            <bool as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <bool as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <bool as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(CredentialProtocolFeatures {
            supportsSelectiveDisclosure,
            supportsPredicateProofs,
            supportsVerifierScopedPseudonym,
            supportsSameHolderProof,
        })
    }
}
impl From<CredentialProtocolFeatures> for midnight_compact_runtime::Value {
    fn from(s: CredentialProtocolFeatures) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.supportsSelectiveDisclosure));
        _v.push(midnight_compact_runtime::Value::from(s.supportsPredicateProofs));
        _v.push(midnight_compact_runtime::Value::from(s.supportsVerifierScopedPseudonym));
        _v.push(midnight_compact_runtime::Value::from(s.supportsSameHolderProof));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for CredentialProtocolFeatures {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.supportsSelectiveDisclosure.binary_repr(writer);
        self.supportsPredicateProofs.binary_repr(writer);
        self.supportsVerifierScopedPseudonym.binary_repr(writer);
        self.supportsSameHolderProof.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.supportsSelectiveDisclosure.binary_len()
            + self.supportsPredicateProofs.binary_len()
            + self.supportsVerifierScopedPseudonym.binary_len()
            + self.supportsSameHolderProof.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct ProtocolMessageEnvelope {
    pub version: u16,
    pub messageId: [u8; 32],
    pub threadId: [u8; 32],
    pub initialMessage: bool,
    pub respondsToMessageId: [u8; 32],
    pub createdAt: u64,
    pub hasExpiresAt: bool,
    pub expiresAt: u64,
}
impl Aligned for ProtocolMessageEnvelope {
    fn alignment() -> Alignment {
        Alignment::concat([
            &<u16 as Aligned>::alignment(),
            &<[u8; 32] as Aligned>::alignment(),
            &<[u8; 32] as Aligned>::alignment(),
            &<bool as Aligned>::alignment(),
            &<[u8; 32] as Aligned>::alignment(),
            &<u64 as Aligned>::alignment(),
            &<bool as Aligned>::alignment(),
            &<u64 as Aligned>::alignment(),
        ])
    }
}
impl FieldRepr for ProtocolMessageEnvelope {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.version.field_repr(writer);
        self.messageId.field_repr(writer);
        self.threadId.field_repr(writer);
        self.initialMessage.field_repr(writer);
        self.respondsToMessageId.field_repr(writer);
        self.createdAt.field_repr(writer);
        self.hasExpiresAt.field_repr(writer);
        self.expiresAt.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.version.field_size()
            + self.messageId.field_size()
            + self.threadId.field_size()
            + self.initialMessage.field_size()
            + self.respondsToMessageId.field_size()
            + self.createdAt.field_size()
            + self.hasExpiresAt.field_size()
            + self.expiresAt.field_size()
    }
}
impl FromFieldRepr for ProtocolMessageEnvelope {
    const FIELD_SIZE: usize = <u16 as FromFieldRepr>::FIELD_SIZE
        + <[u8; 32] as FromFieldRepr>::FIELD_SIZE
        + <[u8; 32] as FromFieldRepr>::FIELD_SIZE
        + <bool as FromFieldRepr>::FIELD_SIZE
        + <[u8; 32] as FromFieldRepr>::FIELD_SIZE
        + <u64 as FromFieldRepr>::FIELD_SIZE
        + <bool as FromFieldRepr>::FIELD_SIZE
        + <u64 as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let version =
            <u16 as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <u16 as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <u16 as FromFieldRepr>::FIELD_SIZE;
        let messageId = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let threadId = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let initialMessage =
            <bool as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <bool as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <bool as FromFieldRepr>::FIELD_SIZE;
        let respondsToMessageId = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let createdAt =
            <u64 as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <u64 as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <u64 as FromFieldRepr>::FIELD_SIZE;
        let hasExpiresAt =
            <bool as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <bool as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <bool as FromFieldRepr>::FIELD_SIZE;
        let expiresAt =
            <u64 as FromFieldRepr>::from_field_repr(&_repr[_offset.._offset + <u64 as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <u64 as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(ProtocolMessageEnvelope {
            version,
            messageId,
            threadId,
            initialMessage,
            respondsToMessageId,
            createdAt,
            hasExpiresAt,
            expiresAt,
        })
    }
}
impl From<ProtocolMessageEnvelope> for midnight_compact_runtime::Value {
    fn from(s: ProtocolMessageEnvelope) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.version));
        _v.push(midnight_compact_runtime::Value::from(s.messageId));
        _v.push(midnight_compact_runtime::Value::from(s.threadId));
        _v.push(midnight_compact_runtime::Value::from(s.initialMessage));
        _v.push(midnight_compact_runtime::Value::from(s.respondsToMessageId));
        _v.push(midnight_compact_runtime::Value::from(s.createdAt));
        _v.push(midnight_compact_runtime::Value::from(s.hasExpiresAt));
        _v.push(midnight_compact_runtime::Value::from(s.expiresAt));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for ProtocolMessageEnvelope {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.version.binary_repr(writer);
        self.messageId.binary_repr(writer);
        self.threadId.binary_repr(writer);
        self.initialMessage.binary_repr(writer);
        self.respondsToMessageId.binary_repr(writer);
        self.createdAt.binary_repr(writer);
        self.hasExpiresAt.binary_repr(writer);
        self.expiresAt.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.version.binary_len()
            + self.messageId.binary_len()
            + self.threadId.binary_len()
            + self.initialMessage.binary_len()
            + self.respondsToMessageId.binary_len()
            + self.createdAt.binary_len()
            + self.hasExpiresAt.binary_len()
            + self.expiresAt.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct StatusRegistryRef {
    pub registryId: [u8; 32],
    pub authorityVerificationMethodRef: VerificationMethodRef,
}
impl Aligned for StatusRegistryRef {
    fn alignment() -> Alignment {
        Alignment::concat([
            &<[u8; 32] as Aligned>::alignment(),
            &<VerificationMethodRef as Aligned>::alignment(),
        ])
    }
}
impl FieldRepr for StatusRegistryRef {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.registryId.field_repr(writer);
        self.authorityVerificationMethodRef.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.registryId.field_size() + self.authorityVerificationMethodRef.field_size()
    }
}
impl FromFieldRepr for StatusRegistryRef {
    const FIELD_SIZE: usize =
        <[u8; 32] as FromFieldRepr>::FIELD_SIZE + <VerificationMethodRef as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let registryId = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let authorityVerificationMethodRef = <VerificationMethodRef as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <VerificationMethodRef as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <VerificationMethodRef as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(StatusRegistryRef {
            registryId,
            authorityVerificationMethodRef,
        })
    }
}
impl From<StatusRegistryRef> for midnight_compact_runtime::Value {
    fn from(s: StatusRegistryRef) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.registryId));
        _v.push(midnight_compact_runtime::Value::from(s.authorityVerificationMethodRef));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for StatusRegistryRef {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.registryId.binary_repr(writer);
        self.authorityVerificationMethodRef.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.registryId.binary_len() + self.authorityVerificationMethodRef.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct NoStatusBinding {}
impl Aligned for NoStatusBinding {
    fn alignment() -> Alignment {
        Alignment::concat([])
    }
}
impl FieldRepr for NoStatusBinding {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {}
    fn field_size(&self) -> usize {
        0
    }
}
impl FromFieldRepr for NoStatusBinding {
    const FIELD_SIZE: usize = 0;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let _ = _offset;
        Some(NoStatusBinding {})
    }
}
impl From<NoStatusBinding> for midnight_compact_runtime::Value {
    fn from(s: NoStatusBinding) -> midnight_compact_runtime::Value {
        midnight_compact_runtime::Value::concat(core::iter::empty::<&midnight_compact_runtime::Value>())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for NoStatusBinding {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        let _ = writer;
    }
    fn binary_len(&self) -> usize {
        0
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
#[repr(u8)]
pub enum StatusType {
    #[default]
    revocationRegistry = 0,
}
impl Aligned for StatusType {
    fn alignment() -> Alignment {
        u8::alignment()
    }
}
impl FieldRepr for StatusType {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        (*self as u8).field_repr(writer);
    }
    fn field_size(&self) -> usize {
        1
    }
}
impl FromFieldRepr for StatusType {
    const FIELD_SIZE: usize = 1;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        let n = u8::from_field_repr(r)?;
        match n {
            0 => Some(Self::revocationRegistry),
            _ => None,
        }
    }
}
impl From<StatusType> for midnight_compact_runtime::Value {
    fn from(v: StatusType) -> midnight_compact_runtime::Value {
        midnight_compact_runtime::Value::from(v as u8)
    }
}
impl midnight_compact_runtime::BinaryHashRepr for StatusType {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        (*self as u8).binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        1
    }
}
#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct RegistryBoundStatusBinding {
    pub statusType: StatusType,
    pub registryRef: StatusRegistryRef,
    pub statusHandleCommitment: [u8; 32],
}
impl Aligned for RegistryBoundStatusBinding {
    fn alignment() -> Alignment {
        Alignment::concat([
            &<StatusType as Aligned>::alignment(),
            &<StatusRegistryRef as Aligned>::alignment(),
            &<[u8; 32] as Aligned>::alignment(),
        ])
    }
}
impl FieldRepr for RegistryBoundStatusBinding {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.statusType.field_repr(writer);
        self.registryRef.field_repr(writer);
        self.statusHandleCommitment.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.statusType.field_size() + self.registryRef.field_size() + self.statusHandleCommitment.field_size()
    }
}
impl FromFieldRepr for RegistryBoundStatusBinding {
    const FIELD_SIZE: usize = <StatusType as FromFieldRepr>::FIELD_SIZE
        + <StatusRegistryRef as FromFieldRepr>::FIELD_SIZE
        + <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let statusType = <StatusType as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <StatusType as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <StatusType as FromFieldRepr>::FIELD_SIZE;
        let registryRef = <StatusRegistryRef as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <StatusRegistryRef as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <StatusRegistryRef as FromFieldRepr>::FIELD_SIZE;
        let statusHandleCommitment = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(RegistryBoundStatusBinding {
            statusType,
            registryRef,
            statusHandleCommitment,
        })
    }
}
impl From<RegistryBoundStatusBinding> for midnight_compact_runtime::Value {
    fn from(s: RegistryBoundStatusBinding) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.statusType));
        _v.push(midnight_compact_runtime::Value::from(s.registryRef));
        _v.push(midnight_compact_runtime::Value::from(s.statusHandleCommitment));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for RegistryBoundStatusBinding {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.statusType.binary_repr(writer);
        self.registryRef.binary_repr(writer);
        self.statusHandleCommitment.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.statusType.binary_len() + self.registryRef.binary_len() + self.statusHandleCommitment.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct ContractAddress {
    pub bytes: [u8; 32],
}
impl Aligned for ContractAddress {
    fn alignment() -> Alignment {
        Alignment::concat([&<[u8; 32] as Aligned>::alignment()])
    }
}
impl FieldRepr for ContractAddress {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.bytes.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.bytes.field_size()
    }
}
impl FromFieldRepr for ContractAddress {
    const FIELD_SIZE: usize = <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(_repr: &[Fr]) -> Option<Self> {
        if _repr.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let bytes = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &_repr[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(ContractAddress { bytes })
    }
}
impl From<ContractAddress> for midnight_compact_runtime::Value {
    fn from(s: ContractAddress) -> midnight_compact_runtime::Value {
        let mut _v: Vec<midnight_compact_runtime::Value> = Vec::new();
        _v.push(midnight_compact_runtime::Value::from(s.bytes));
        midnight_compact_runtime::Value::concat(_v.iter())
    }
}
impl midnight_compact_runtime::BinaryHashRepr for ContractAddress {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.bytes.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.bytes.binary_len()
    }
}

pub trait Witnesses<PS> {}
impl<PS> Witnesses<PS> for NoWitnesses {}

pub struct Contract<PS, W = NoWitnesses>
where
    W: Witnesses<PS>,
{
    pub witnesses: W,
    _ps: PhantomData<PS>,
}

impl<PS, W> Contract<PS, W>
where
    PS: Clone,
    W: Witnesses<PS>,
{
    pub fn new(witnesses: W) -> Self {
        Self {
            witnesses,
            _ps: PhantomData,
        }
    }
    pub fn initial_state(&self, ctx: ConstructorContext<PS>) -> Result<ConstructorResult<PS>, CompactError> {
        let sv = new_array(vec![]);
        let state = ChargedState::new(sv);
        let qctx = QueryContext::new(state, midnight_compact_runtime::ContractAddress::default());
        Ok(ConstructorResult {
            current_contract_state: qctx.state,
            current_private_state: ctx.initial_private_state,
            current_zswap_local_state: ctx.empty_zswap_local_state,
        })
    }
}

pub struct Ledger<'a, D: DB = DefaultDB> {
    state: &'a ChargedState<D>,
}

pub fn ledger<D: DB>(state: &ChargedState<D>) -> Ledger<'_, D> {
    Ledger { state }
}

impl<'a, D: DB> Ledger<'a, D> {}

pub mod pure_circuits {
    use super::*;

    pub fn no_schema_family_resolver_hint() -> Result<[u8; 32], CompactError> {
        Ok([
            109u8, 105, 100, 110, 105, 103, 104, 116, 58, 118, 99, 58, 115, 99, 104, 101, 109, 97, 58, 110, 111, 45,
            104, 105, 110, 116, 0, 0, 0, 0, 0, 0,
        ])
    }

    pub fn assert_valid_schema_ref(schema: SchemaRef) -> Result<(), CompactError> {
        compact_assert!(
            (schema.packageId
                != [
                    0u8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                ]),
            "Schema package id must be set"
        );
        compact_assert!(
            (schema.schemaId
                != [
                    0u8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                ]),
            "Schema id must be set"
        );
        let t = schema.majorVersion;
        compact_assert!((t > 0), "Schema major version must be positive");
        Ok(())
    }

    pub fn assert_valid_schema_capabilities(capabilities: SchemaCapabilities) -> Result<(), CompactError> {
        Ok(())
    }

    pub fn assert_valid_schema_family_resolution_hint(hint: SchemaFamilyResolutionHint) -> Result<(), CompactError> {
        let no_hint = pure_circuits::no_schema_family_resolver_hint()?;
        Ok(if hint.hasResolverHint {
            compact_assert!((hint.resolverHint != no_hint), "Schema resolver hint must be set");
            compact_assert!(
                (hint.resolverHint
                    != [
                        0u8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0
                    ]),
                "Schema resolver hint must not be empty"
            );
        } else {
            compact_assert!(
                (hint.resolverHint == no_hint),
                "Absent schema resolver hint must use the no-hint sentinel"
            );
        })
    }

    pub fn assert_valid_schema_descriptor(descriptor: SchemaDescriptor) -> Result<(), CompactError> {
        pure_circuits::assert_valid_schema_ref(descriptor.schema.clone())?;
        pure_circuits::assert_valid_schema_capabilities(descriptor.capabilities.clone())?;
        Ok(pure_circuits::assert_valid_schema_family_resolution_hint(
            descriptor.familyResolutionHint.clone(),
        )?)
    }

    pub fn assert_matching_schema_capabilities(
        expected: SchemaCapabilities,
        actual: SchemaCapabilities,
    ) -> Result<(), CompactError> {
        compact_assert!(
            ((((expected.supportsSelectiveDisclosure == actual.supportsSelectiveDisclosure)
                && (expected.supportsPredicateProofs == actual.supportsPredicateProofs))
                && (expected.supportsVerifierScopedPseudonym == actual.supportsVerifierScopedPseudonym))
                && (expected.supportsSameHolderProof == actual.supportsSameHolderProof)),
            "Schema capabilities mismatch"
        );
        Ok(())
    }

    pub fn verify_signature(pk: JubjubPoint, signature: Signature, challenge: Fr) -> Result<bool, CompactError> {
        let left_side = midnight_compact_runtime::ec_mul_generator(signature.s.clone());
        let c_pk = midnight_compact_runtime::ec_mul(pk.clone(), challenge);
        let right_side = midnight_compact_runtime::ec_add(signature.r.clone(), c_pk.clone());
        let x_matches = (midnight_compact_runtime::jubjub_point_x(left_side.clone())
            == midnight_compact_runtime::jubjub_point_x(right_side.clone()));
        let y_matches = (midnight_compact_runtime::jubjub_point_y(left_side.clone())
            == midnight_compact_runtime::jubjub_point_y(right_side.clone()));
        compact_assert!((x_matches && y_matches), "Signature verification failed");
        Ok((x_matches && y_matches))
    }

    pub fn issuance_context_tag() -> Result<[u8; 32], CompactError> {
        Ok([
            109u8, 105, 100, 110, 105, 103, 104, 116, 58, 118, 99, 58, 105, 115, 115, 117, 97, 110, 99, 101, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0,
        ])
    }

    pub fn presentation_context_tag() -> Result<[u8; 32], CompactError> {
        Ok([
            109u8, 105, 100, 110, 105, 103, 104, 116, 58, 118, 99, 58, 112, 114, 101, 115, 101, 110, 116, 97, 116, 105,
            111, 110, 0, 0, 0, 0, 0, 0, 0, 0,
        ])
    }

    pub fn status_attestation_context_tag() -> Result<[u8; 32], CompactError> {
        Ok([
            109u8, 105, 100, 110, 105, 103, 104, 116, 58, 118, 99, 58, 115, 116, 97, 116, 117, 115, 45, 97, 116, 116,
            101, 115, 116, 97, 116, 105, 111, 110, 0, 0,
        ])
    }

    pub(crate) fn proof_payload_root_for_context(
        body_root: [u8; 32],
        context_tag: [u8; 32],
        proof: Proof,
    ) -> Result<[u8; 32], CompactError> {
        Ok(midnight_compact_runtime::std_lib::persistent_hash_aligned(&[
            midnight_compact_runtime::AlignedValue::from(body_root),
            midnight_compact_runtime::AlignedValue::from(context_tag),
            midnight_compact_runtime::AlignedValue::from(midnight_compact_runtime::std_lib::persistent_hash_aligned(
                &[midnight_compact_runtime::AlignedValue::from(
                    proof.signerVerificationMethodRef,
                )],
            )),
            midnight_compact_runtime::AlignedValue::from(midnight_compact_runtime::upgrade_from_transient(
                midnight_compact_runtime::std_lib::transient_hash_aligned(&[
                    midnight_compact_runtime::AlignedValue::from(proof.createdAt),
                ]),
            )),
            midnight_compact_runtime::AlignedValue::from(proof.challengeHash),
        ]))
    }

    pub(crate) fn proof_challenge_for_context(
        body_root: [u8; 32],
        context_tag: [u8; 32],
        proof: Proof,
    ) -> Result<Fr, CompactError> {
        Ok(midnight_compact_runtime::degrade_to_transient(
            midnight_compact_runtime::std_lib::persistent_hash_aligned(&[
                midnight_compact_runtime::AlignedValue::from(pure_circuits::proof_payload_root_for_context(
                    body_root,
                    context_tag,
                    proof.clone(),
                )?),
                midnight_compact_runtime::AlignedValue::from(midnight_compact_runtime::upgrade_from_transient(
                    midnight_compact_runtime::std_lib::transient_hash_aligned(&[
                        midnight_compact_runtime::AlignedValue::from(proof.publicKey),
                    ]),
                )),
                midnight_compact_runtime::AlignedValue::from(midnight_compact_runtime::upgrade_from_transient(
                    midnight_compact_runtime::std_lib::transient_hash_aligned(&[
                        midnight_compact_runtime::AlignedValue::from(proof.signature.r),
                    ]),
                )),
            ]),
        ))
    }

    pub(crate) fn assert_valid_proof_for_context(
        body_root: [u8; 32],
        context_tag: [u8; 32],
        proof: Proof,
    ) -> Result<(), CompactError> {
        compact_assert!(
            pure_circuits::verify_signature(
                proof.publicKey.clone(),
                proof.signature.clone(),
                pure_circuits::proof_challenge_for_context(body_root, context_tag, proof.clone())?
            )?,
            "Proof verification failed"
        );
        Ok(())
    }

    pub fn issuance_proof_payload_root(body_root: [u8; 32], proof: Proof) -> Result<[u8; 32], CompactError> {
        Ok(pure_circuits::proof_payload_root_for_context(
            body_root,
            pure_circuits::issuance_context_tag()?,
            proof.clone(),
        )?)
    }

    pub fn presentation_proof_payload_root(body_root: [u8; 32], proof: Proof) -> Result<[u8; 32], CompactError> {
        Ok(pure_circuits::proof_payload_root_for_context(
            body_root,
            pure_circuits::presentation_context_tag()?,
            proof.clone(),
        )?)
    }

    pub fn issuance_proof_challenge(body_root: [u8; 32], proof: Proof) -> Result<Fr, CompactError> {
        Ok(pure_circuits::proof_challenge_for_context(
            body_root,
            pure_circuits::issuance_context_tag()?,
            proof.clone(),
        )?)
    }

    pub fn presentation_proof_challenge(body_root: [u8; 32], proof: Proof) -> Result<Fr, CompactError> {
        Ok(pure_circuits::proof_challenge_for_context(
            body_root,
            pure_circuits::presentation_context_tag()?,
            proof.clone(),
        )?)
    }

    pub fn assert_valid_issuance_context_proof(body_root: [u8; 32], proof: Proof) -> Result<(), CompactError> {
        Ok(pure_circuits::assert_valid_proof_for_context(
            body_root,
            pure_circuits::issuance_context_tag()?,
            proof.clone(),
        )?)
    }

    pub fn assert_valid_presentation_context_proof(body_root: [u8; 32], proof: Proof) -> Result<(), CompactError> {
        Ok(pure_circuits::assert_valid_proof_for_context(
            body_root,
            pure_circuits::presentation_context_tag()?,
            proof.clone(),
        )?)
    }

    pub fn status_attestation_proof_payload_root(body_root: [u8; 32], proof: Proof) -> Result<[u8; 32], CompactError> {
        Ok(pure_circuits::proof_payload_root_for_context(
            body_root,
            pure_circuits::status_attestation_context_tag()?,
            proof.clone(),
        )?)
    }

    pub fn status_attestation_proof_challenge(body_root: [u8; 32], proof: Proof) -> Result<Fr, CompactError> {
        Ok(pure_circuits::proof_challenge_for_context(
            body_root,
            pure_circuits::status_attestation_context_tag()?,
            proof.clone(),
        )?)
    }

    pub fn assert_valid_status_attestation_context_proof(
        body_root: [u8; 32],
        proof: Proof,
    ) -> Result<(), CompactError> {
        Ok(pure_circuits::assert_valid_proof_for_context(
            body_root,
            pure_circuits::status_attestation_context_tag()?,
            proof.clone(),
        )?)
    }

    pub fn assert_valid_explicit_holder_binding(binding: ExplicitHolderBinding) -> Result<(), CompactError> {
        compact_assert!(
            (binding.holderVerificationMethodRef.didContractAddress.bytes
                != [
                    0u8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                ]),
            "Explicit holder binding DID contract address must be set"
        );
        compact_assert!(
            (binding.holderVerificationMethodRef.methodId
                != [
                    0u8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                ]),
            "Explicit holder binding method reference must be set"
        );
        Ok(())
    }

    pub fn assert_matching_explicit_holder_bindings(
        credential_binding: ExplicitHolderBinding,
        presentation_binding: ExplicitHolderBinding,
    ) -> Result<(), CompactError> {
        compact_assert!(
            (presentation_binding.holderVerificationMethodRef.didContractAddress
                == credential_binding.holderVerificationMethodRef.didContractAddress),
            "Presentation holder contract does not match credential holder binding"
        );
        compact_assert!(
            (presentation_binding.holderVerificationMethodRef.methodId
                == credential_binding.holderVerificationMethodRef.methodId),
            "Presentation holder method reference does not match credential holder binding"
        );
        Ok(())
    }

    pub fn assert_proof_matches_explicit_holder_binding(
        binding: ExplicitHolderBinding,
        presentation_proof: Proof,
    ) -> Result<(), CompactError> {
        compact_assert!(
            (binding.holderVerificationMethodRef.didContractAddress
                == presentation_proof.signerVerificationMethodRef.didContractAddress),
            "Presentation proof signer must match holder binding"
        );
        compact_assert!(
            (binding.holderVerificationMethodRef.methodId == presentation_proof.signerVerificationMethodRef.methodId),
            "Presentation proof signer method reference must match holder binding"
        );
        Ok(())
    }

    pub fn assert_valid_jubjub_holder_binding(binding: JubjubHolderBinding) -> Result<(), CompactError> {
        compact_assert!(
            ((midnight_compact_runtime::jubjub_point_x(binding.holderPublicKey.clone()) != Fr::from(0u64))
                || (midnight_compact_runtime::jubjub_point_y(binding.holderPublicKey.clone()) != Fr::from(0u64))),
            "Jubjub holder binding public key must be set"
        );
        Ok(())
    }

    pub fn assert_matching_jubjub_holder_bindings(
        credential_binding: JubjubHolderBinding,
        presentation_binding: JubjubHolderBinding,
    ) -> Result<(), CompactError> {
        compact_assert!(
            ((midnight_compact_runtime::jubjub_point_x(presentation_binding.holderPublicKey.clone())
                == midnight_compact_runtime::jubjub_point_x(credential_binding.holderPublicKey.clone()))
                && (midnight_compact_runtime::jubjub_point_y(presentation_binding.holderPublicKey.clone())
                    == midnight_compact_runtime::jubjub_point_y(credential_binding.holderPublicKey.clone()))),
            "Presentation Jubjub holder key does not match the credential holder binding"
        );
        Ok(())
    }

    pub fn assert_proof_matches_jubjub_holder_binding(
        binding: JubjubHolderBinding,
        presentation_proof: Proof,
    ) -> Result<(), CompactError> {
        compact_assert!(
            ((midnight_compact_runtime::jubjub_point_x(binding.holderPublicKey.clone())
                == midnight_compact_runtime::jubjub_point_x(presentation_proof.publicKey.clone()))
                && (midnight_compact_runtime::jubjub_point_y(binding.holderPublicKey.clone())
                    == midnight_compact_runtime::jubjub_point_y(presentation_proof.publicKey.clone()))),
            "Presentation proof public key must match the Jubjub holder binding"
        );
        Ok(())
    }

    pub fn assert_valid_offchain_midnight_holder_binding(
        binding: OffchainMidnightHolderBinding,
    ) -> Result<(), CompactError> {
        compact_assert!(
            (binding.holderDidStateHash
                != [
                    0u8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                ]),
            "Offchain Midnight holder state hash must be set"
        );
        compact_assert!(
            (binding.holderMethodId
                != [
                    0u8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                ]),
            "Offchain Midnight holder method id must be set"
        );
        let jubjub_binding = JubjubHolderBinding {
            holderPublicKey: binding.holderPublicKey,
        };
        Ok(pure_circuits::assert_valid_jubjub_holder_binding(
            jubjub_binding.clone(),
        )?)
    }

    pub fn assert_matching_offchain_midnight_holder_bindings(
        credential_binding: OffchainMidnightHolderBinding,
        presentation_binding: OffchainMidnightHolderBinding,
    ) -> Result<(), CompactError> {
        compact_assert!(
            (presentation_binding.holderDidStateHash == credential_binding.holderDidStateHash),
            "Offchain Midnight holder state hash does not match the credential holder binding"
        );
        compact_assert!(
            (presentation_binding.holderMethodId == credential_binding.holderMethodId),
            "Offchain Midnight holder method id does not match the credential holder binding"
        );
        let credential_jubjub_binding = JubjubHolderBinding {
            holderPublicKey: credential_binding.holderPublicKey,
        };
        let presentation_jubjub_binding = JubjubHolderBinding {
            holderPublicKey: presentation_binding.holderPublicKey,
        };
        Ok(pure_circuits::assert_matching_jubjub_holder_bindings(
            credential_jubjub_binding.clone(),
            presentation_jubjub_binding.clone(),
        )?)
    }

    pub fn assert_proof_matches_offchain_midnight_holder_binding(
        binding: OffchainMidnightHolderBinding,
        presentation_proof: Proof,
    ) -> Result<(), CompactError> {
        let jubjub_binding = JubjubHolderBinding {
            holderPublicKey: binding.holderPublicKey,
        };
        Ok(pure_circuits::assert_proof_matches_jubjub_holder_binding(
            jubjub_binding.clone(),
            presentation_proof.clone(),
        )?)
    }

    pub fn no_secret_holder_challenge_response() -> Result<[u8; 32], CompactError> {
        Ok([
            109u8, 105, 100, 110, 105, 103, 104, 116, 58, 118, 99, 58, 110, 111, 45, 104, 111, 108, 100, 101, 114, 45,
            114, 101, 115, 112, 111, 110, 115, 101, 0, 0,
        ])
    }

    pub fn secret_holder_binding_commitment(
        holder_secret: [u8; 32],
        opening: [u8; 32],
    ) -> Result<[u8; 32], CompactError> {
        Ok(midnight_compact_runtime::persistent_commit(
            &holder_secret,
            midnight_compact_runtime::base_crypto::hash::HashOutput(opening),
        )
        .0)
    }

    pub fn secret_holder_binding_challenge_response(
        holder_secret: [u8; 32],
        verifier_challenge_hash: [u8; 32],
    ) -> Result<[u8; 32], CompactError> {
        Ok(midnight_compact_runtime::std_lib::persistent_hash_aligned(&[
            midnight_compact_runtime::AlignedValue::from([
                109u8, 105, 100, 110, 105, 103, 104, 116, 58, 118, 99, 58, 104, 111, 108, 100, 101, 114, 45, 99, 104,
                97, 108, 108, 0, 0, 0, 0, 0, 0, 0, 0,
            ]),
            midnight_compact_runtime::AlignedValue::from(holder_secret),
            midnight_compact_runtime::AlignedValue::from(verifier_challenge_hash),
        ]))
    }

    pub fn verifier_scoped_pseudonym(
        holder_secret: [u8; 32],
        verifier_domain_hash: [u8; 32],
    ) -> Result<[u8; 32], CompactError> {
        Ok(midnight_compact_runtime::std_lib::persistent_hash_aligned(&[
            midnight_compact_runtime::AlignedValue::from([
                109u8, 105, 100, 110, 105, 103, 104, 116, 58, 118, 99, 58, 104, 111, 108, 100, 101, 114, 45, 112, 115,
                101, 117, 100, 111, 110, 121, 109, 0, 0, 0, 0,
            ]),
            midnight_compact_runtime::AlignedValue::from(holder_secret),
            midnight_compact_runtime::AlignedValue::from(verifier_domain_hash),
        ]))
    }

    pub fn assert_verifier_scoped_pseudonym(
        pseudonym: [u8; 32],
        holder_secret: [u8; 32],
        verifier_domain_hash: [u8; 32],
    ) -> Result<(), CompactError> {
        compact_assert!(
            (pseudonym == pure_circuits::verifier_scoped_pseudonym(holder_secret, verifier_domain_hash)?),
            "Verifier-scoped pseudonym does not match the holder secret and verifier domain"
        );
        Ok(())
    }

    pub fn blinded_secret_holder_commitment(
        holder_secret_commitment: [u8; 32],
        issuer_nonce: [u8; 32],
        blinding_factor: [u8; 32],
    ) -> Result<[u8; 32], CompactError> {
        Ok(midnight_compact_runtime::std_lib::persistent_hash_aligned(&[
            midnight_compact_runtime::AlignedValue::from([
                109u8, 105, 100, 110, 105, 103, 104, 116, 58, 118, 99, 58, 98, 108, 105, 110, 100, 45, 104, 111, 108,
                100, 101, 114, 0, 0, 0, 0, 0, 0, 0, 0,
            ]),
            midnight_compact_runtime::AlignedValue::from(holder_secret_commitment),
            midnight_compact_runtime::AlignedValue::from(issuer_nonce),
            midnight_compact_runtime::AlignedValue::from(blinding_factor),
        ]))
    }

    pub fn assert_valid_secret_holder_credential_binding(binding: SecretHolderBinding) -> Result<(), CompactError> {
        compact_assert!(
            (binding.requestChallengeResponse == pure_circuits::no_secret_holder_challenge_response()?),
            "Credential secret holder binding must not embed a request challenge response"
        );
        Ok(())
    }

    pub fn assert_valid_secret_holder_presentation_binding(binding: SecretHolderBinding) -> Result<(), CompactError> {
        compact_assert!(
            (binding.requestChallengeResponse != pure_circuits::no_secret_holder_challenge_response()?),
            "Presentation secret holder binding must include a request challenge response"
        );
        Ok(())
    }

    pub fn assert_matching_secret_holder_bindings(
        credential_binding: SecretHolderBinding,
        presentation_binding: SecretHolderBinding,
    ) -> Result<(), CompactError> {
        compact_assert!(
            (credential_binding.holderSecretCommitment == presentation_binding.holderSecretCommitment),
            "Presentation holder secret commitment does not match the credential holder binding"
        );
        Ok(())
    }

    pub fn assert_valid_blinded_secret_holder_credential_binding(
        binding: BlindedSecretHolderBinding,
    ) -> Result<(), CompactError> {
        compact_assert!(
            (binding.requestChallengeResponse == pure_circuits::no_secret_holder_challenge_response()?),
            "Credential blinded holder binding must not embed a request challenge response"
        );
        Ok(())
    }

    pub fn assert_valid_blinded_secret_holder_presentation_binding(
        binding: BlindedSecretHolderBinding,
    ) -> Result<(), CompactError> {
        compact_assert!(
            (binding.requestChallengeResponse != pure_circuits::no_secret_holder_challenge_response()?),
            "Presentation blinded holder binding must include a request challenge response"
        );
        Ok(())
    }

    pub fn assert_matching_blinded_secret_holder_bindings(
        credential_binding: BlindedSecretHolderBinding,
        presentation_binding: BlindedSecretHolderBinding,
    ) -> Result<(), CompactError> {
        compact_assert!(
            (credential_binding.blindedHolderSecretCommitment == presentation_binding.blindedHolderSecretCommitment),
            "Presentation blinded holder commitment does not match the credential holder binding"
        );
        compact_assert!(
            (credential_binding.issuerNonce == presentation_binding.issuerNonce),
            "Presentation issuer nonce does not match the credential holder binding"
        );
        Ok(())
    }

    pub fn assert_secret_holder_binding_witness(
        binding: SecretHolderBinding,
        verifier_challenge_hash: [u8; 32],
        holder_secret: [u8; 32],
        opening: [u8; 32],
    ) -> Result<(), CompactError> {
        compact_assert!(
            (pure_circuits::secret_holder_binding_commitment(holder_secret, opening)?
                == binding.holderSecretCommitment),
            "Holder secret witness does not match the holder-binding commitment"
        );
        compact_assert!(
            (pure_circuits::secret_holder_binding_challenge_response(holder_secret, verifier_challenge_hash)?
                == binding.requestChallengeResponse),
            "Holder secret challenge response does not match the verifier challenge"
        );
        Ok(())
    }

    pub fn assert_blinded_secret_holder_binding_witness(
        binding: BlindedSecretHolderBinding,
        verifier_challenge_hash: [u8; 32],
        holder_secret: [u8; 32],
        opening: [u8; 32],
        blinding_factor: [u8; 32],
    ) -> Result<(), CompactError> {
        let holder_commitment = pure_circuits::secret_holder_binding_commitment(holder_secret, opening)?;
        compact_assert!(
            (pure_circuits::blinded_secret_holder_commitment(
                holder_commitment.clone(),
                binding.issuerNonce.clone(),
                blinding_factor
            )? == binding.blindedHolderSecretCommitment),
            "Blinded holder commitment does not match the hidden holder secret witness"
        );
        compact_assert!(
            (pure_circuits::secret_holder_binding_challenge_response(holder_secret, verifier_challenge_hash)?
                == binding.requestChallengeResponse),
            "Blinded holder challenge response does not match the verifier challenge"
        );
        Ok(())
    }

    pub fn protocol_features_as_schema_capabilities(
        features: CredentialProtocolFeatures,
    ) -> Result<SchemaCapabilities, CompactError> {
        Ok(SchemaCapabilities {
            supportsSelectiveDisclosure: features.supportsSelectiveDisclosure,
            supportsPredicateProofs: features.supportsPredicateProofs,
            supportsVerifierScopedPseudonym: features.supportsVerifierScopedPseudonym,
            supportsSameHolderProof: features.supportsSameHolderProof,
        })
    }

    pub fn assert_protocol_features_match_schema_capabilities(
        features: CredentialProtocolFeatures,
        capabilities: SchemaCapabilities,
    ) -> Result<(), CompactError> {
        Ok(pure_circuits::assert_matching_schema_capabilities(
            pure_circuits::protocol_features_as_schema_capabilities(features.clone())?,
            capabilities.clone(),
        )?)
    }

    pub fn no_protocol_response_reference() -> Result<[u8; 32], CompactError> {
        Ok([
            109u8, 105, 100, 110, 105, 103, 104, 116, 58, 118, 99, 58, 112, 114, 111, 116, 111, 99, 111, 108, 58, 110,
            111, 110, 101, 0, 0, 0, 0, 0, 0, 0,
        ])
    }

    pub fn assert_valid_verification_method_ref(
        verification_method_ref: VerificationMethodRef,
    ) -> Result<(), CompactError> {
        compact_assert!(
            (verification_method_ref.methodId
                != [
                    0u8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                ]),
            "Verification method reference must be set"
        );
        Ok(())
    }

    pub fn assert_matching_schema_refs(expected: SchemaRef, actual: SchemaRef) -> Result<(), CompactError> {
        pure_circuits::assert_valid_schema_ref(expected.clone())?;
        pure_circuits::assert_valid_schema_ref(actual.clone())?;
        compact_assert!(
            ((((expected.packageId == actual.packageId) && (expected.schemaId == actual.schemaId))
                && (expected.majorVersion == actual.majorVersion))
                && (expected.minorVersion == actual.minorVersion)),
            "Schema reference mismatch"
        );
        Ok(())
    }

    pub fn assert_valid_protocol_message_envelope(envelope: ProtocolMessageEnvelope) -> Result<(), CompactError> {
        let no_response = pure_circuits::no_protocol_response_reference()?;
        compact_assert!((envelope.version == 1), "Protocol message version mismatch");
        compact_assert!((envelope.messageId != no_response), "Protocol message id must be set");
        compact_assert!((envelope.threadId != no_response), "Protocol thread id must be set");
        if envelope.initialMessage {
            compact_assert!(
                (envelope.respondsToMessageId == no_response),
                "Initial protocol message must not reference a previous message"
            );
        } else {
            compact_assert!(
                (envelope.respondsToMessageId != no_response),
                "Protocol response message must reference a previous message"
            );
        }
        Ok(if envelope.hasExpiresAt {
            let t = envelope.expiresAt;
            compact_assert!(
                (t >= envelope.createdAt),
                "Protocol message expiration must not precede creation"
            );
        })
    }

    pub fn assert_protocol_response_envelope(
        request_envelope: ProtocolMessageEnvelope,
        response_envelope: ProtocolMessageEnvelope,
    ) -> Result<(), CompactError> {
        pure_circuits::assert_valid_protocol_message_envelope(request_envelope.clone())?;
        pure_circuits::assert_valid_protocol_message_envelope(response_envelope.clone())?;
        compact_assert!(
            (!(response_envelope.initialMessage)),
            "Protocol response must not be initial"
        );
        compact_assert!(
            (response_envelope.threadId == request_envelope.threadId),
            "Protocol response thread id does not match the request thread id"
        );
        compact_assert!(
            (response_envelope.respondsToMessageId == request_envelope.messageId),
            "Protocol response does not reference the request message id"
        );
        let t = response_envelope.createdAt;
        compact_assert!(
            (t >= request_envelope.createdAt),
            "Protocol response creation time must not precede the request"
        );
        Ok(())
    }

    pub fn assert_valid_status_registry_ref(registry_ref: StatusRegistryRef) -> Result<(), CompactError> {
        compact_assert!(
            (registry_ref.registryId
                != [
                    0u8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                ]),
            "Status registry id must be set"
        );
        Ok(pure_circuits::assert_valid_verification_method_ref(
            registry_ref.authorityVerificationMethodRef.clone(),
        )?)
    }

    pub fn assert_valid_no_status_binding(binding: NoStatusBinding) -> Result<(), CompactError> {
        Ok(())
    }

    pub fn assert_valid_registry_bound_status_binding(binding: RegistryBoundStatusBinding) -> Result<(), CompactError> {
        compact_assert!(
            (binding.statusType == StatusType::revocationRegistry),
            "Registry-bound status type must be revocationRegistry"
        );
        pure_circuits::assert_valid_status_registry_ref(binding.registryRef.clone())?;
        compact_assert!(
            (binding.statusHandleCommitment
                != [
                    0u8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
                ]),
            "Status handle commitment must be set"
        );
        Ok(())
    }

    pub fn registry_bound_status_binding_root(binding: RegistryBoundStatusBinding) -> Result<[u8; 32], CompactError> {
        pure_circuits::assert_valid_registry_bound_status_binding(binding.clone())?;
        Ok(midnight_compact_runtime::std_lib::persistent_hash_aligned(&[
            midnight_compact_runtime::AlignedValue::from(binding),
        ]))
    }

    pub fn assert_same_secret_holder_binding_witnesses(
        first_binding: SecretHolderBinding,
        second_binding: SecretHolderBinding,
        verifier_challenge_hash: [u8; 32],
        holder_secret: [u8; 32],
        first_opening: [u8; 32],
        second_opening: [u8; 32],
    ) -> Result<(), CompactError> {
        compact_assert!(
            (first_binding.holderSecretCommitment != second_binding.holderSecretCommitment),
            "Same-holder proof requires two distinct credential bindings"
        );
        pure_circuits::assert_secret_holder_binding_witness(
            first_binding.clone(),
            verifier_challenge_hash,
            holder_secret,
            first_opening,
        )?;
        Ok(pure_circuits::assert_secret_holder_binding_witness(
            second_binding.clone(),
            verifier_challenge_hash,
            holder_secret,
            second_opening,
        )?)
    }

    pub fn assert_same_secret_holder_binding_witnesses3(
        first_binding: SecretHolderBinding,
        second_binding: SecretHolderBinding,
        third_binding: SecretHolderBinding,
        verifier_challenge_hash: [u8; 32],
        holder_secret: [u8; 32],
        first_opening: [u8; 32],
        second_opening: [u8; 32],
        third_opening: [u8; 32],
    ) -> Result<(), CompactError> {
        compact_assert!(
            (first_binding.holderSecretCommitment != second_binding.holderSecretCommitment),
            "Same-holder proof requires distinct first and second credential bindings"
        );
        compact_assert!(
            (first_binding.holderSecretCommitment != third_binding.holderSecretCommitment),
            "Same-holder proof requires distinct first and third credential bindings"
        );
        compact_assert!(
            (second_binding.holderSecretCommitment != third_binding.holderSecretCommitment),
            "Same-holder proof requires distinct second and third credential bindings"
        );
        pure_circuits::assert_secret_holder_binding_witness(
            first_binding.clone(),
            verifier_challenge_hash,
            holder_secret,
            first_opening,
        )?;
        pure_circuits::assert_secret_holder_binding_witness(
            second_binding.clone(),
            verifier_challenge_hash,
            holder_secret,
            second_opening,
        )?;
        Ok(pure_circuits::assert_secret_holder_binding_witness(
            third_binding.clone(),
            verifier_challenge_hash,
            holder_secret,
            third_opening,
        )?)
    }

    pub fn assert_same_blinded_secret_holder_binding_witnesses(
        first_binding: BlindedSecretHolderBinding,
        second_binding: BlindedSecretHolderBinding,
        verifier_challenge_hash: [u8; 32],
        holder_secret: [u8; 32],
        first_opening: [u8; 32],
        first_blinding_factor: [u8; 32],
        second_opening: [u8; 32],
        second_blinding_factor: [u8; 32],
    ) -> Result<(), CompactError> {
        compact_assert!(
            (first_binding.blindedHolderSecretCommitment != second_binding.blindedHolderSecretCommitment),
            "Same-holder proof requires two distinct credential bindings"
        );
        pure_circuits::assert_blinded_secret_holder_binding_witness(
            first_binding.clone(),
            verifier_challenge_hash,
            holder_secret,
            first_opening,
            first_blinding_factor,
        )?;
        Ok(pure_circuits::assert_blinded_secret_holder_binding_witness(
            second_binding.clone(),
            verifier_challenge_hash,
            holder_secret,
            second_opening,
            second_blinding_factor,
        )?)
    }

    pub fn assert_same_blinded_secret_holder_binding_witnesses3(
        first_binding: BlindedSecretHolderBinding,
        second_binding: BlindedSecretHolderBinding,
        third_binding: BlindedSecretHolderBinding,
        verifier_challenge_hash: [u8; 32],
        holder_secret: [u8; 32],
        first_opening: [u8; 32],
        first_blinding_factor: [u8; 32],
        second_opening: [u8; 32],
        second_blinding_factor: [u8; 32],
        third_opening: [u8; 32],
        third_blinding_factor: [u8; 32],
    ) -> Result<(), CompactError> {
        compact_assert!(
            (first_binding.blindedHolderSecretCommitment != second_binding.blindedHolderSecretCommitment),
            "Same-holder proof requires distinct first and second credential bindings"
        );
        compact_assert!(
            (first_binding.blindedHolderSecretCommitment != third_binding.blindedHolderSecretCommitment),
            "Same-holder proof requires distinct first and third credential bindings"
        );
        compact_assert!(
            (second_binding.blindedHolderSecretCommitment != third_binding.blindedHolderSecretCommitment),
            "Same-holder proof requires distinct second and third credential bindings"
        );
        pure_circuits::assert_blinded_secret_holder_binding_witness(
            first_binding.clone(),
            verifier_challenge_hash,
            holder_secret,
            first_opening,
            first_blinding_factor,
        )?;
        pure_circuits::assert_blinded_secret_holder_binding_witness(
            second_binding.clone(),
            verifier_challenge_hash,
            holder_secret,
            second_opening,
            second_blinding_factor,
        )?;
        Ok(pure_circuits::assert_blinded_secret_holder_binding_witness(
            third_binding.clone(),
            verifier_challenge_hash,
            holder_secret,
            third_opening,
            third_blinding_factor,
        )?)
    }
}
